### ISSUE TITLE
Create a separate resource type for each UCP plane

### ISSUE THREAD

**Issue by rynowak** [radius-project/radius#4290]
Forking off from a discussion in https://github.com/project-radius/radius/pull/3493/files#diff-95dbdd451b47bf002fb28d7dfe9835e6eba318925b57426b90f057451e3f043b

Currently we use the same controller implementation and resource type for **all** UCP planes. The resource type has a discriminator field for the `kind` of plane. This design is not straightforward and pushes a lot of complexity into the public API of Radius. Discriminators should be avoided except when they are the last resort. 

A comparatively simpler design is to use a different resource type and controller for each plane. This way we don't see features leak between the different planes, and can simplify the API. The URL structure already reflects the design we want, but the resource body does not. Our controller framework has evolved significantly since we started on UCP and we can take advantage of that by pivoting the design. 

[AB#4504](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/4504)

**Comment by sylvainsf** [comment]
@rynowak is this still valid?

**Comment by rynowak** [comment]
This is done. Closing.
