### ISSUE TITLE
Test_ETCDClient/save_can_update_matching_etag is flaky

### ISSUE THREAD

**Issue by rynowak** [radius-project/radius#5046]
Test `Test_ETCDClient/save_can_update_matching_etag` failed in this run https://github.com/project-radius/radius/actions/runs/4028714856/jobs/6925886086

Unfortunately it's a timeout so there isn't much information available. 

```txt
    shared.go:237: 
        	Error Trace:	/runner/_work/radius/radius/pkg/ucp/store/etcdstore/shared.go:237
        	Error:      	Received unexpected error:
        	            	etcdserver: request timed out
        	Test:       	Test_ETCDClient/save_can_update_matching_etag
```

[AB#5885](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/5885)

**Comment by kachawla** [comment]
Closing since this hasn't been linked to a test failure in over a year, please re-open if we see this again.
