### ISSUE TITLE
Draft Plan for communication expectations with the community

### ISSUE THREAD

**Issue by sylvainsf** [radius-project/radius#5323]
Involve Sarah and have a brown bag to socialize. 

End goal is a document to engage with the community
1. Respond to Bugs
2. Feature request
3. Discord and Teams messages

this document should be reviewed via design review meeting

[AB#6674](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/6674)

**Comment by AaronCrawfis** [comment]
This has been completed as part of launch activities and communication
