### ISSUE TITLE
Design: extend the use-cases of Applications.Core/secretStores

### ISSUE THREAD

**Issue by youngbupark** [radius-project/radius#5520]
## Overview of feature request

[TLS termination specification](https://github.com/project-radius/radius/issues/2310#issuecomment-1516802963) proposes the use-case of gateway for Applications.Core/secretStores. Beyond this use-case, we want to extend the capability of secretstores to the other radius resources, such as `Applications.Core/containers`. 

This issue is to investigate the other scenarios and use-cases for non-gateway resources.

[AB#7794](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/7794)

**Comment by rynowak** [comment]
@superbeeny - should we assign to you?
