### ISSUE TITLE
Modify getRecipeData api

### ISSUE THREAD

**Issue by AaronCrawfis** [radius-project/radius#5546]
API needs to be modified from environments/{environmentName}/{recipeName}/getmetadata to environments/{environmentName}/getrecipemetadata 
We need to support having a [request body](bookmark://_Example_API_Request:) 
Recipe name should be pulled from request body instead of from url 
API:
```
/{rootScope}/providers/Applications.Core/environments/{environmentName}/getrecipemetadata
```

Example API Request: 
```
Path: /{rootScope}/providers/Applications.Core/environments/env1/mongotest/getmetadata?api-version=2022-03-15-privatepreview 
```
Method: POST 

Example API Body:
```
{ 

  "recipeName": "mongotest" 
} 
```

Example API Response:  
```
{ 

  "parameters": { 
    "rootScope": "/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/testGroup", 
    "api-version": "2022-03-15-privatepreview", 
    "environmentName": "env0", 
    "recipeName": "mongotest" 
  }, 
  "responses": { 
    "200": { 
      "body": { 
        "linkType": "Applications.Link/mongoDatabases", 
        "templatePath": "br:sampleregistry.azureacr.io/radius/recipes/cosmosdb", 
        "parameters": { 
          "throughput": { 
            "type" : "int", 
            "defaultValue" : 400 
          }, 
          "location": { 
            "type" : "string", 
            "defaultValue" : "[resourceGroup().location]" 
          } 
        } 
      } 
    } 
  } 
}
```

[AB#7908](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/7908)

**Comment by kachawla** [comment]
@AaronCrawfis this was updated in https://github.com/radius-project/radius/pull/5480/files. Anything else that's open here or can we close this? Also, could you help me understand what's expected out of https://github.com/radius-project/radius/issues/5547?

**Comment by AaronCrawfis** [comment]
> this was updated in https://github.com/radius-project/radius/pull/5480/files. Anything else that's open here or can we close this?

Sounds like we can close this

> Also, could you help me understand what's expected out of https://github.com/radius-project/radius/issues/5547?

Added some context here: https://github.com/radius-project/radius/issues/5547#issuecomment-1908776811
