### ISSUE TITLE
Environment validation in `rad env create` is wrong

### ISSUE THREAD

**Issue by rynowak** [radius-project/radius#5698]
### Steps to reproduce (required)

1. Create two kubernetes clusters and install Radius on one of them (Cluster A)
2. Create radius workspace pointing to Cluster A
3. Create namespace `test-ns` on Cluster A (`kubectl create ns test-ns`)
4. Set Cluster B as your default cluster in Kubeconfig
5. Run `rad env create kubernetes test-env --namespace test-ns`

### Observed behavior (required)

The `test-ns` namespace will be created on Cluster B by the `rad` CLI.

### Desired behavior (required)

The `test-ns` namespace should be created on Cluster A. 

### Workaround (optional)

Use kubectl 😆 

### rad Version (required)

v0.21

## Additional context

The bug is [here](https://github.com/project-radius/radius/blob/4d80a343b4c19e0374439a2e067137ea620a022e/pkg/cli/cmd/env/namespace/namespace.go#LL34C1-L34C1). This code is using the current Kubernetes context rather than the context set in the workspace.

Outside of installation, our code should never use the default Kubernetes context. It should always come from the workspace. 

[AB#8248](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/8248)

**Comment by jhandel** [comment]
this does not look like a CLI bug.. the correct context is being passed to (if digging through the variables in the debugger is to be believed)

"/apis/api.ucp.dev/v1alpha3/planes/radius/local/resourceGroups/default/providers/Applications.Core/environments/test-env"

**Comment by rynowak** [comment]
Thanks @jhandel for fixing this 👍
