### ISSUE TITLE
Specify container restart policy

### ISSUE THREAD

**Issue by AaronCrawfis** [radius-project/radius#578]
**Overview of feature request**
Radius users should be able to specify the behavior of a stopped container in the restartPolicy property, choosing between never, always, or onfailure.

```bicep
  resource nodeapplication 'Components' = {
    name: 'nodeapp'
    kind: 'radius.dev/Container@v1alpha1'
    properties: {
      run: {
        container: {
          image: 'radiusteam/tutorial-nodeapp'
        }
        restartPolicy: 'always'
        ...
```

## Estimation (number of half days)

2

[AB#4126](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/4126)

**Comment by shubham1172** [comment]
Hi, please assign this issue to me!

**Comment by rynowak** [comment]
Thanks @shubham1172 assigning to you. 

Can you tell me more about the assign command? what would that do?

**Comment by shubham1172** [comment]
> Thanks @shubham1172 assigning to you. 
> 
> Can you tell me more about the assign command? what would that do? 

Thanks @rynowak, it can assign the issue to any contributor who comments '/assign', so that maintainers don't have to manually do it.

Example implementation: https://github.com/dapr/dapr/blob/master/.github/scripts/dapr_bot.js#L206

**Comment by rynowak** [comment]
@shubham1172 - sounds cool! please do.
