### ISSUE TITLE
First app experience CLI: Simplify application delete

### ISSUE THREAD

**Issue by Reshrahim** [radius-project/radius#6004]
## Summary
Captured as part of a usability study with first-app experience

The user thought his app name was app.bicep, because that is the file he spent the most time working with.
To delete his application, he attempted to delete app.bicep, which failed

## Proposed actions:
We should extrapolate from an attempt to delete app.bicep that the customer is attempting to delete first-app
Also, we know rad app delete app.bicep will fail, so we should not prompt the user with "Are you sure you want to delete app.bicep.”  We should instead prompt them to clarify they are attempting to delete first-app

[AB#8886](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/8886)

**Comment by AaronCrawfis** [comment]
This was completed as part of 6039
