### ISSUE TITLE
Poor error handling for language evaluation failures in bicep recipes

### ISSUE THREAD

**Issue by rynowak** [radius-project/radius#6046]
### Steps to reproduce (required)

I've written a function test for this issue. Search for the issue number in our codebase to find it.

### Observed behavior (required)

Error is reported like with JSON-encoding text inside a string, inside a JSON response. This can't be easily parsed or understood by a user.

The output is similar to #6045

### Desired behavior (required)

Error is reported in a reasonable format.

### Workaround (optional)

Not blocked, this is a bad error message.

[AB#8939](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/8939)

[AB#8940](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/8940)

**Comment by AaronCrawfis** [comment]
Addressed by #6551
