### ISSUE TITLE
Clean up Route resources from codebase

### ISSUE THREAD

**Issue by nithyatsu** [radius-project/radius#6099]
We should clean up Route resources from Radius codebase before OSS since DNS-SD support without the need for routes is now available. This is necessary to avoid open sourcing the routes implementation while we want Radius users to move away from using this concept. 

[AB#9043](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/9043)

**Comment by willtsai** [comment]
reopening this issue to address removing httpRoutes from the eshop sample (https://github.com/radius-project/samples/pull/574)
