### ISSUE TITLE
Refactor Terraform Execute

### ISSUE THREAD

**Issue by sk593** [radius-project/radius#6180]
## Overview of feature request

There's a lot of code within the Terraform package that is being reused. We aren't able to refactor without further investigation due to the use of defer functions. We should look into if it's possible to refactor the shared code  

## Acceptance criteria

1. Investigate shared code and identify areas to refactor (specifically with respect to use of defer functions)
2. Implement refactoring decisions 

## Additional context

This has been discussed in previous PRs but further investigation is needed

[AB#9203](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/9203)

**Comment by kachawla** [comment]
https://github.com/radius-project/radius/pull/6630 and https://github.com/radius-project/radius/pull/6644 have deduplicated a significant amount of repeated code, so I will be closing this issue. The Terraform installation call should occur within the scope of each individual API, allowing for installation cleanup to be deferred until the corresponding API operation is complete. Please re-open this issue if anything else should be investigated further.
