### ISSUE TITLE
Dapr release download within the workflow sometimes gets 403

### ISSUE THREAD

**Issue by ytimocin** [radius-project/radius#6213]
### Steps to reproduce (required)
1. Some workflow runs fail with a 403 code from Dapr.

### Observed behavior (required)
See this run: https://github.com/radius-project/radius/actions/runs/6075876574/job/16483097337.
```
❌  cannot get the latest release version: https://api.github.com/repos/dapr/dashboard/releases - 403 Forbidden
❌  Deploying the Dapr dashboard with latest version to your cluster...
```

### Desired behavior (required)
Not getting 403 during the Dapr download from GitHub.

### Workaround (optional)
Rerunning the run works.

## Additional context

[AB#9268](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/9268)

**Comment by rynowak** [comment]
I merged another fix for this. If we continue to see the problem we can reactivate this issue.
