### ISSUE TITLE
Simplify API Registration - DatastoresRP, DaprRP, MessagingRP

### ISSUE THREAD

**Issue by lakshmimsft** [radius-project/radius#6269]
## Overview of feature request

Ref: https://github.com/radius-project/radius/pull/5851

@youngbupark and @rynowak  helped update current service, httproutes, operations and api registration for corerp. 
The remaining RPs (DatastoresRP, DaprRP, MessagingRP) will need to have code updated to conform to updated api registration and merging of 'applications.datastores' service into now updated 'radius' service.

## Acceptance criteria
Code updated in DatastoresRP, DaprRP, MessagingRP for updated API registration using as reference updates done in pkg/corerp/setup and associated files in corerp. 
Single service 'radius' will serve all resource providers in radius.

## Additional context

[AB#9362](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/9362)

**Comment by AaronCrawfis** [comment]
Reopening so we can finish out some cleanup
