### ISSUE TITLE
Create new recipe test with azure storage resource

### ISSUE THREAD

**Issue by youngbupark** [radius-project/radius#6293]
## Bug information

[Test_MongoDB_Recipe_ContextParameter](https://github.com/project-radius/radius/blob/f7cd3e500451cb325773004d6ca4020106b3ad7a/test/functional/shared/resources/mongodb_test.go#L195) is testing the recipe creating CosmosDB resources. However, CosmosDB resource is not a good resource since it spends many minutes for creating and deleting.

It is better to replace `Test_MongoDB_Recipe_ContextParameter` with new test which uses Azure storage. Azure storage doesn't require lots of time to create and delete the resources. 

[AB#8803](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/8803)

[AB#9498](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/9498)

[AB#10943](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/10943)

**Comment by kachawla** [comment]
We can use either Azure storage resource or [MongoDB on Kubernetes](https://github.com/radius-project/recipes/blob/main/local-dev/mongodatabases.bicep), given that value-backed recipes and the extender resource are now supported with recipes.

To provide more context on why we initially chose CosmosDB: During the first phase of the end-to-end recipes implementation, the Mongo portable resource was the first and only resource implemented to support recipes at the time. Support for Kubernetes resources was only introduced later when we added output values support in the authored recipe. So the selection of CosmosDB was not arbitrary; it was the only feasible option at that time. The intention was to transition away from Azure resources wherever possible in favor of Kubernetes support once it was in place, but it ended up not getting prioritized.

**Comment by kachawla** [comment]
Handled it in https://github.com/radius-project/radius/pull/7041. Since the main goal of Test_MongoDB_Recipe_ContextParameter is to verify that the context parameter is successfully populated, we don't need dependency on creating a resource for this test, added a new test that validates context few fields in the context parameter without actually provisioning any resources.
