### ISSUE TITLE
Support user-assigned managed identities in `rad install kubernetes`

### ISSUE THREAD

**Issue by infbase** [radius-project/radius#6370]
**Overview of feature request**

Support the option of using a user-assigned managed identity for Azure provider instead of a service principal.
A `--provider-azure-mi` parameter may be introduced for the UAMI resource id, for instance, to be used instead of `--provider-azure-client-id` + `--provider-azure-client-secret` in these cases.

A positive side-effect of this is not having to redeploy components to the cluster when secrets rotate, for instance.

[AB#6166](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/6166)

[AB#12061](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/12061)

**Comment by willtsai** [comment]
resolving in favor of https://github.com/radius-project/radius/issues/7308
