### ISSUE TITLE
rad should validate that the AWS region specified (in the flag or interactive) is a valid region

### ISSUE THREAD

**Issue by asilverman** [radius-project/radius#6373]
## **Overview of feature request**

Since rad doesn't do this at the moment, if the user makes a mistake they will need to reinstall the radius control plane which is not a great user experience. Preferably instead of statically whitelisting the values we should fetch them from AWS API (as new regions can and will be added over time)

Use the equivalent REST API to get the following (reference https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_DescribeRegions.html)
```bash
aws ec2 describe-regions --all-regions --output json | jq ".Regions[].RegionName"
"af-south-1"
"eu-north-1"
"ap-south-1"
"eu-west-3"
"eu-west-2"
"eu-south-1"
"eu-west-1"
"ap-northeast-3"
"ap-northeast-2"
"me-south-1"
"ap-northeast-1"
"me-central-1"
"sa-east-1"
"ca-central-1"
"ap-east-1"
"ap-southeast-1"
"ap-southeast-2"
"ap-southeast-3"
"eu-central-1"
"us-east-1"
"us-east-2"
"us-west-1"
"us-west-2"
```

## Definition of done:
- [x] radius-project/radius#3922 
- [ ] https://github.com/project-radius/radius/issues/5155
- [ ]  For flags we should validate that the value provided belongs to the set
- [ ]  Add unit tests

**Comment by Reshrahim** [comment]
This is fixed by listing the available AWS regions and prompting the user to pick one from the list.
