### ISSUE TITLE
Running `rad` commands following the expiration of a `az login` token results in an error

### ISSUE THREAD

**Issue by asilverman** [radius-project/radius#6377]
## Bug information
```bash
rad env init kubernetes -i
Error: Invoking Azure CLI failed with the following error: ERROR: AADSTS700082: The refresh token has expired due to inactivity. The token was issued on 2022-06-20T20:43:20.8185544Z and was inactive for 90.00:00:00.
Trace ID: f182c1fe-da93-48cd-a0d4-efe9d8b32600
Correlation ID: 5c57c084-5838-4f8c-9727-efc2d76770dc
Timestamp: 2022-09-28 20:37:14Z
To re-authenticate, please run:
az login --scope https://management.azure.com//.default
```
### Steps to reproduce (required)

1. Run `az login`
2. Wait for the token to expire
3. Run `rad env init kubernetes -i`

### Desired behavior (required)

`rad` should prompt you to authenticate (by childing a process that runs `az login` ) instead of failing

### rad Version (required)
```json
{
  "release": "edge",
  "version": "v0.11.0-185-g553a231",
  "bicep": "0.7.29",
  "commit": "553a231a6cfa9c01df7e7e095079d208104cb6de"
}
```

### Operating system (required)
Win10 WSL2

## Additional context

[AB#4127](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/4127)

**Comment by willtsai** [comment]
Since this experience has been improved upon and the error message is actually quite detailed, we are closing this for now.
