### ISSUE TITLE
Clarify user experience for re-deployment of Link with updated recipe template

### ISSUE THREAD

**Issue by kachawla** [radius-project/radius#6379]
Scenarios that need more clarity -
* Existing connector re-deployed with new template path - should underlying resources be updated and previous resources deleted?
* Existing connector re-deployed with same template path - should we try to re-deploy the template or skip recipe deployment? (this scenario will be handled by clarity around versioning of templates, if a template with same version is provided again it will be ignored else re-deployed)
* Do we want to support modifications to a previously deployed resource through recipe template?

[AB#4154](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/4154)

**Comment by rynowak** [comment]
@kachawla - do you think this is a dupe of https://github.com/radius-project/radius/issues/6372? Could we combine these items?

**Comment by kachawla** [comment]
> @kachawla - do you think this is a dupe of #6372? Could we combine these items?

Yeah, you're right. All the scenarios here will be resolved by versioning.
