### ISSUE TITLE
Kubernetes Integration - Helm Support

### ISSUE THREAD

**Issue by lakshmimsft** [radius-project/radius#6431]
## Overview of feature request

Add a Kubernetes-centric configuration experience to help enable trivial adoption of Radius for applications that use the Kubernetes application model (Deployment, Service, etc.) for configuration and use the common Kubernetes toolchains for application deployment (Helm, Flux). 

Ref for further Detail: [Design Document](https://github.com/radius-project/design-notes/blob/3d98c6be4c47a4f6a12bc834a22ceae670ab3c92/architecture/2023-10-kubernetes-integration.md)

## Acceptance criteria
1. Use can edit a Helm chart, adding each annotation to each Kubernetes Deployment indicating that Radius should be enabled (radapp.io/enabled: 'true'). Upon merging updates,  the metadata is updated in deployments, which automatically triggers the create of a Radius application and container resources that belong to that application.
1. Users will be able to create recipes using a new CRD type (Recipe) that can be used for any type of resource that supports recipes

## Additional context

[AB#9672](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/9672)

**Comment by rynowak** [comment]
This is done :) - there's a tail of small improvements to make but the features exist and have documentation.
