### ISSUE TITLE
Public Preview Release Criteria

### ISSUE THREAD

**Issue by nicolejms** [radius-project/radius#6472]
Areas | Criteria | Done
 -- | -- | -- 
Documentation | All getting started and sample documentation in place and   verified |  X |
| | Sample automation run on release candidate |  X  | 
Defects | No P0 or P1 defects at release |  X |
  | No defects in release path/sprint | X |  
E2E coverage | E2E scenarios defined and validated |  X |  
  | 100% of scenarios automated |  X |
  | plan in place and executed for manual tests (CLI   testing on Windows and Mac) |  X |
  | Ad-hoc bug bash on release candidate | X   |
Test Pass Rate | 100% automated P0 and P1 tests passing |  X |
  | 95% automated P2 tests passing | X |
Reliability | n/a |  |  
Code Coverage | >60% |   X |
Supportability | Troubleshooting Guides (internal and user facing) | X | 
  | Communication plan in place for escalations (templates, triage, on-call, discord) | X |
| | List of known issues for v.026 |  |
  | Patching strategy in place |  |
Performance testing | Baseline established for installation time |  |
  | Baseline established for sample deployment on   "cold" system | X| 
Security | No   MSRC defects in release | X  | 
Customers | 3 customers signed up |   X |
  | Known customer scenarios executed successfully |  |
Release Readiness | Installation steps verified | X| |

</body>

</html>

[AB#9726](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/9726)

**Comment by AaronCrawfis** [comment]
Closing as completed
