### ISSUE TITLE
rad init UI can be cut off on a small terminal

### ISSUE THREAD

**Issue by rynowak** [radius-project/radius#6492]
### Steps to reproduce (required)

Make your terminal pretty small.

Run `rad init`

### Observed behavior (required)

This is what I see:

<img width="567" alt="image" src="https://github.com/radius-project/radius/assets/1430011/f2163907-5f91-4371-8076-de4628ba8055">

### Desired behavior (required)

`rad init` UI works

### Workaround (optional)

Resize terminal

[AB#9829](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/9829)

**Comment by shalabhms** [comment]
Related: https://github.com/radius-project/radius/issues/6264

**Comment by willtsai** [comment]
@vishwahiremat - please check if this is the same issue as https://github.com/radius-project/radius/issues/5467 and if so, please close #5467 as a duplicate

**Comment by vishwahiremat** [comment]
> @vishwahiremat - please check if this is the same issue as #5467 and if so, please close #5467 as a duplicate

@willtsai  wanted to confirm this is a different issue, working on a fix for this.
