### ISSUE TITLE
Migrate helm chart to ghcr.io

### ISSUE THREAD

**Issue by rynowak** [radius-project/radius#6502]
## Overview of feature request

We had originally planned to move our Helm Chart to `ghcr.io` as part of publicizing the repo. At the last minute we ran into issues pulling and installing the chart in the CLI, so we reverted the changed and kept pulling from ACR.

## Acceptance criteria

Support pull/install in `rad init` from GHCR.

Remove publish to ACR (might want to delay).

Update documentation.

[AB#9841](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/9841)

**Comment by willdavsmith** [comment]
Reopening because we reverted the PR that fixed this
