### ISSUE TITLE
Fix dev recipe logic by updating client to find them in ghcr

### ISSUE THREAD

**Issue by willdavsmith** [radius-project/radius#6506]
## Overview of feature request

Today, we hard-code the list of dev recipes to use for `rad init`. We should instead call to `ghcr.io/radius-project` and list our dev recipes from there.

## Acceptance criteria

* dev recipes are fetched dynamically from GHCR

## Additional context

[AB#9843](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/9843)

**Comment by lakshmimsft** [comment]
We will implement Recipe Packs to define the set of recipes to register. For now keeping the hard coded list of local dev recipes.
