### ISSUE TITLE
rad init generates app.bicep with an unavailable image 

### ISSUE THREAD

**Issue by abtin** [radius-project/radius#6518]
### Steps to reproduce (required)
Follow the steps on the [getting started page](https://docs.radapp.io/getting-started/)
Run `rad init` and then `rad run app.bicep` 

You'd get the famous ImagePullBackOff error:
`"message": "Container state is 'Waiting' Reason: ImagePullBackOff, Message: Back-off pulling image \"ghcr.io/radius-project/tutorial/webapp:edge\""`

### Observed behavior (required)
In the `app.bicep` the container image used is `image: 'ghcr.io/radius-project/tutorial/webapp:edge'` which appears to be unavailable to public.

If you switch the container to `image: 'radius.azurecr.io/samples/demo:latest'` the application runs successfully!

### Desired behavior (required)
`rad run app.bicep` should work.

### Workaround (optional)
Either `rad init` should generate the `app.bicep` with an available image like `'radius.azurecr.io/samples/demo:latest'` or `ghcr.io/radius-project/tutorial/webapp:edge'` should be made available to the public.

### rad Version (required)
RELEASE   VERSION   BICEP     COMMIT
0.26.6    v0.26.6   0.11.90   5e02b8a1706e7697d031db84a176f7c3f2053ee2

### Operating system (required)
MacOS Ventura 13.6 (22G120) on Apple M2

## Additional context

[AB#9862](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/9862)

**Comment by AaronCrawfis** [comment]
Thanks for reporting @abtin! #6520 adds a fix for this.

As a mitigation I've pushed `ghcr.io/radius-project/samples/demo:edge` in order to fix the current behavior.
