### ISSUE TITLE
Unable to run functional tests locally

### ISSUE THREAD

**Issue by vinayada1** [radius-project/radius#6556]
### Steps to reproduce (required)
Run a functional test locally that uses functional.GetMagpieImage() as a parameter to the bicep.

The pod fails due to missing magpie image in GHCR. I am seeing this error:-
Message: rpc error: code = NotFound desc = failed to pull and unpack image \"ghcr.io/radius-project/dev/magpiego:latest\": failed to resolve reference \"ghcr.io/radius-project/dev/magpiego:latest\": ghcr.io/radius-project/dev/magpiego:latest: not found",

### Observed behavior (required)
In GHCR, there seems to be no image with the "latest" tag. This would not be a problem in CI/CD because there we run with the pr tag.

### Desired behavior (required)
We should be able to run the functional tests locally as is.

### Workaround (optional)
Can make a local change to pick an image that exists as a workaround

### rad Version (required)

0.26.3

### Operating system (required)

macOS

## Additional context

[AB#9898](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/9898)

**Comment by rynowak** [comment]
We should make sure this image is getting pushed when a commit happens on `main`.

**Comment by willdavsmith** [comment]
currently, we push to `ghcr.io/radius-project/magpiego:latest`. We should switch this publish step to `ghcr.io/radius-project/dev/magpiego:latest`

https://github.com/radius-project/radius/pkgs/container/magpiego
