### ISSUE TITLE
Unable to run recipe functional tests locally

### ISSUE THREAD

**Issue by vinayada1** [radius-project/radius#6603]
### Steps to reproduce (required)
Run a recipe functional test locally. (e.g. Test_Redis_Recipe)

### Observed behavior (required)
I see the following error:-
"message": "failed to fetch repository from the path \"ghcr.io/radius-project/dev/test/functional/shared/recipes/redis-recipe-value-backed:latest\": ghcr.io/radius-project/dev/test/functional/shared/recipes/redis-recipe-value-backed:latest: not found"

### Desired behavior (required)
We should be able to run the test as is in local debugging environment.

### Workaround (optional)

Set BICEP_RECIPE_TAG_VERSION to an existing version published to ghcr found on https://github.com/orgs/radius-project/packages

### rad Version (required)
0.26.3

## Additional context
This is not a problem in CI/CD as the tests use the PR tag for the recipes and they do get published with the PR tag before running the tests

[AB#9978](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/9978)

**Comment by shalabhms** [comment]
triage: we need to fix this issue as it blocks the inner loop - testing recipe functional tests.
