### ISSUE TITLE
Enable OpenSSF Scorecard

### ISSUE THREAD

**Issue by kachawla** [radius-project/radius#6612]
## Overview of feature request
[OSSF Scorecard](https://github.com/ossf/scorecard/) automatically runs several checks, and enabling it in Radius can help identify security vulnerabilities. Full list of checks it runs can be found at https://github.com/ossf/scorecard/#checks-1 and https://github.com/ossf/scorecard/blob/main/docs/checks.md.

We can leverage its GitHub action to enable the scorecard https://github.com/ossf/scorecard/#scorecard-github-action.

## Acceptance criteria

The [Scorecard GitHub action](https://github.com/ossf/scorecard-action) is enabled and is passing.

[AB#9987](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/9987)

**Comment by AaronCrawfis** [comment]
This looks like a great thing to add! Their process allows for a just a couple clicks to open a PR with the GitHub Action already pre-generated and ready. Should just take a minute or two. And as part of the same PR we can add the badge to our README.

**Comment by kachawla** [comment]
@AaronCrawfis Thanks for adding details. Yeah it is fairly quick to setup, I'll try this right now. Main thing to that might require further investigation is if any of the checks fail after this is enabled.
