### ISSUE TITLE
`main: line 79: type: curl: not found` error in Ubuntu

### ISSUE THREAD

**Issue by ytimocin** [radius-project/radius#6629]
### Steps to reproduce (required)
1. `docker run -ti --rm ubuntu /bin/bash` command is to start Ubuntu container locally.
2. Within the container I run `apt update && apt upgrade` and `apt install wget` to install **wget**.
4. Then I download Radius by running `wget -q "https://raw.githubusercontent.com/radius-project/radius/main/deploy/install.sh" -O - | /bin/bash`.
5. Radius is installed but I get the following error `main: line 79: type: curl: not found` as the first output of the **wget** command right above.

### Observed behavior (required)
![image](https://github.com/radius-project/radius/assets/5220939/f0ab80ee-3a35-44e1-8ac2-aff5a0a2f688)

### Desired behavior (required)
No error that says: `main: line 79: type: curl: not found`. Should we update the error message saying that `curl` couldn't be found continuing with `wget` or something like that?

### Workaround (optional)
If I run `apt install curl`, I don't see the error.

### rad Version (required)
RELEASE   VERSION   BICEP     COMMIT
0.26.9    v0.26.9   0.11.90   421a2aeef9e0a8a5c487a8ad6b17719c4826e350

### Operating system (required)
aarch64 - Ubuntu - Docker

## Additional context

[AB#10005](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/10005)

**Comment by youngbupark** [comment]
script is handling curl and wget properly. but we uses `> /dev/null` instead of `&> /dev/null`. In linux bash `>` doesn't catch error whereas zsh in mac catches error out. 

https://github.com/radius-project/radius/blob/c0accc62ac3791d5c5ee90958749a395db51877b/deploy/install.sh#L78-L87
