### ISSUE TITLE
rewrite rad cli connections to use graph API

### ISSUE THREAD

**Issue by nithyatsu** [radius-project/radius#6631]
Currently, CLI uses its own logic to retrieve resources and make an application graph. 
We should rewrite this to use server side getgraph API. 

[AB#10006](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/10006)

**Comment by shalabhms** [comment]
triage: need to have discussion around this to evaluate the performance and decide based on it.
