### ISSUE TITLE
Auto-completion for Radius CLI

### ISSUE THREAD

**Issue by ytimocin** [radius-project/radius#6635]
## Overview of feature request
I am not sure if there is an issue created for this but are we thinking about an autocompletion feature for Radius? Like adding scripts for Bash and Zsh (for example) so that it would be easier for users to get more familiar with Rad CLI.

## Acceptance criteria
Rad CLI should be auto-completable after running some scripts.

## Additional context

[AB#10011](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/10011)

**Comment by AaronCrawfis** [comment]
@ytimocin have you tried `rad completion`? https://docs.radapp.io/reference/cli/rad_completion/

**Comment by ytimocin** [comment]
Thanks @AaronCrawfis! This is working great for me!
