### ISSUE TITLE
Getting "http: server gave HTTP response to HTTPS client." error publishing bicep recipe to a k3d managed registery

### ISSUE THREAD

**Issue by vishwahiremat** [radius-project/radius#6648]
### Steps to reproduce (required)

1. Created a k3d managed registery using command `k3d registry create myregistry.localhost`
2. run rad bicep publish command to publish bicep recipe to newly created registry
`rad bicep publish --file rabbitmq-recipe.bicep --target br:localhost:60964/rabbitmq-recipe:1.0`

### Observed behavior (required)

I am hitting "http: server gave HTTP response to HTTPS client."  error.
![image](https://github.com/radius-project/radius/assets/100623239/ff17d687-93aa-4a26-a92a-535e1a8d22b5)

### Desired behavior (required)

rad bicep publish command should successfully able to publish the recipe to k3d managed registry.
### rad Version (required)

 ~  rad version                                                                                                                                                         ✔  9s
RELEASE   VERSION   BICEP     COMMIT
0.26.9    v0.26.9   0.11.90   421a2aeef9e0a8a5c487a8ad6b17719c4826e350

### Operating system (required)

macOS Sonoma 14.1 M1 chip

## Additional context

[AB#10044](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/10044)

**Comment by rynowak** [comment]
@vishwahiremat is this done?

**Comment by vishwahiremat** [comment]
> @vishwahiremat is this done?

@rynowak yes its done. Closing the issue.

**Comment by rynowak** [comment]
Great 👍
