### ISSUE TITLE
Update `/ok-to-test` command so it can only be triggered by approvers-radius

### ISSUE THREAD

**Issue by AaronCrawfis** [radius-project/radius#6715]
Today `/ok-to-test` can be run by the Radius-Eng team. We should switch this to approvers-radius instead. This is required as we move to open governance.

[AB#10289](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/10289)

**Comment by nicolejms** [comment]
Thought this was done. needs to be done soon.

**Comment by kachawla** [comment]
Was probing around this code and decided to update it while I was at it https://github.com/radius-project/radius/pull/6732
