### ISSUE TITLE
[Proposal] Improve functional test reliability

### ISSUE THREAD

**Issue by youngbupark** [radius-project/radius#6726]
## Problem

The functional tests are designed to validate major Radius features from end to end comprehensively. Radius testing infrastructure executes the functional tests with the following strategies:

| Type | Purpose | Test Sets | Cluster Type | Target Branch | Trigger |
|------|-----------|-----------|--------------|---------------|---------|
| [PR Gating](https://github.com/radius-project/radius/actions/workflows/functional-test.yaml?query=event%3Arepository_dispatch) | Functional correctness by new code change | Functional Tests | Kind in GitHub Action Hosted VM | Contributor's PR Branch | `ok-to-test` |
| [Scheduled Test](https://github.com/radius-project/radius/actions/workflows/functional-test.yaml?query=event%3Aschedule) | Functional correctness | Functional Tests | Kind in GitHub Action Hosted VM | Main Branch | Every 4 hours on weekdays, every 12 hours on weekends |
| [Long Running Tests](https://github.com/radius-project/radius/actions/workflows/long-running-azure.yaml) | Service reliability | Functional Tests | AKS Cluster | Main Branch | Every 2 hours |

So far, we have observed following problems in the failed tests:

| Issue | Description | Resolution |
|----|----|----|
| Build infrastructure issues | network and GitHub Action hosted VM failures | **Beyond our control** |
| External dependency issues | ARM/AWS endpoint and blob/container registry failures | **relieved by adding retry but, beyond our control** |
| Conflicted cloud resource names | Test code tried to create a test resource with the same name when multiple functional tests are running | Resolved by randomizing resource name and leveraging shared resource |
| Race condition | Test code defect | Resolved |
| Resource creation limits | Test code created too many test resources. | Resolved by periodic clean up workflow |
| Service unavailabile or unexpected timeouts | Service pod was restarting when resource usage hits the resource limit and test code failed. | Resolved cpu/memory leak |

We have resolved most of issues by implementing randomized resource names, adding retry logic, and enabling a test resource purge workflow. However, we still see the test failures by service unavailable and timeout from applications-rp and UCP pods even though the tests use only localhost network.

## Proposal

We propose to leverage long-running test and investigate its service metrics to resolve the flakiness of functional tests which is related to the reliability rather than functional correctness.

Based on prior investigation, when the test driver code gets a service unavailable response or a timeout issue, it typically stems from two scenarios:

1. The API server of Kind cluster becomes unresponsive due to the limited resources of the build VM.
2. POD restart occurs when the resource usage of applications-rp exceeds the pod's resource limits.

While adding retry logic in the test driver code might provide a short-term mitigation, it fails to address the underlying long-term issues. To thoroughly investigate these issues, this proposes re-enabling long-running tests and monitoring system metrics from Radius services before making any changes in our code.

Since we resolved all known memory leak issues in the Radius services before, we have introduced new several features, including terraform recipe, which could potentially lead to unknown resource leaks. For instance, deploying multiple Terraform recipes in test spawns multiple new Terraform CLI processes inside container, which can lead to unexpected Pod restart.

Instead of making ad-hoc changes, this proposal recommends to find the actual root cause from the metrics and logs first by following action items:

- [x] Re-enable long-running test pipeline and monitor memory and cpu usage while running all functional tests.
- [x] Run long-running test for a couple of weeks and investigate all unexpected behaviors represented by metrics and logs. 
- [x] Make the right fix from the RCA. For example, (If resource usage hits the limit) Increase the CPU and memory limit for `applications-rp` resource or increase replicas of `applications-rp` from 1 to 2+.
- [x] Enable proactive alerts for long-running tests.
- [x] Create the troubleshooting guide for how to investigate the problems.

[AB#10296](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/10296)

**Comment by youngbupark** [comment]
Due to the private cluster restriction, we cannot use GitHub Actions hosted pool for long-running test which access K8s API-server. So we need to install self-host runner inside cluster and long-running test workflow should use this self-host runner

## actions items.
1. Create AKS cluster in portal with arcpool for self-host runner agent and private cluster configuration
2. Export Template on portal before deploying AKS cluster
3. Install AKS cluster
4. Install Arc controller to arc pool - https://github.com/actions/actions-runner-controller/tree/master
   > we need to restrict agent install to only arc pool
6. Configure forked radius repo to use self-host runner in AKS cluster (for testing purpose)
7. Validate self-host runner works as expected - change longrunning test workflow - https://github.com/youngbupark/radius/blob/main/.github/workflows/long-running-azure.yaml
8. Update bicep template to have the latest change by referring armtemplate from step 2
9. Validate bicep template

## Production
1. Delete long-running test RG
2. redeploy by bicep template
3. Configure self-host runner in radius-project/radius
4. Update workflow
5. Load Grafana dashboard to new grafana dashboard
6. log analytics

**Comment by youngbupark** [comment]
@ytimocin  @shalabhms what's the progress of this work ?

**Comment by ytimocin** [comment]
I think this is fully done @sylvainsf @nicolejms

**Comment by ytimocin** [comment]
I will also mark this as complete.
