### ISSUE TITLE
Failure while working from a fork in the main radius repo

### ISSUE THREAD

**Issue by vinayada1** [radius-project/radius#6778]
### Steps to reproduce (required)
Create a PR from a fork

### Observed behavior (required)
I am seeing the error below on PR: https://github.com/radius-project/radius/actions/runs/6881544056/job/18718115787?pr=6739
[
<img width="1018" alt="Screenshot 2023-11-15 at 10 46 06 AM" src="https://github.com/radius-project/radius/assets/28875764/f20d3d0d-7659-4f2c-9292-c7d771309ba5">
](url)

### Desired behavior (required)
I should be able to create a PR and run all the checks

### Workaround (optional)
Use a branch off the main repo instead of fork

### rad Version (required)
0.26.8    v0.26.8   0.11.90   63855a034997dd77c989c80f2f1c7d28247cb991

### Operating system (required)

macOS Sonoma

## Additional context

[AB#10308](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/10308)

**Comment by rynowak** [comment]
@vinayada1 - is this happening before or after your environment changes?

**Comment by vinayada1** [comment]
Looks like the failure mentioned here is due to my environment changes (didn't realize this was related). I tried a test PR from a fork and I still see a failure...although different (https://github.com/radius-project/radius/actions/runs/6883810700/job/18725096618?pr=6784) :-
![Screenshot 2023-11-15 at 2 54 15 PM](https://github.com/radius-project/radius/assets/28875764/619967d6-83a5-4572-b617-0c45e4f7106c)

**Comment by rynowak** [comment]
Looks like a new regression from https://github.com/radius-project/radius/pull/6716/files#diff-69250281a3f8b6ed9c93d9d9d8d92aa49e2105c37fe83fd22168ec5ab85250bdR17

/cc @AaronCrawfis
