### ISSUE TITLE
`failed to get informer from cache` error in the controller

### ISSUE THREAD

**Issue by ytimocin** [radius-project/radius#6794]
## Bug information

`
{"severity":"error","timestamp":"2023-11-16T22:22:35.602Z","name":"controller.controller-runtime.source.EventHandler","caller":"source/kind.go:68","message":"failed to get informer from cache","serviceName":"controller","version":"edge","hostName":"controller-55b5c964c5-g28vl","error":"failed to get API group resources: unable to retrieve the complete list of server APIs: radapp.io/v1alpha3: the server could not find the requested resource","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/source.(*Kind).Start.func1.1\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.15.0/pkg/internal/source/kind.go:68\nk8s.io/apimachinery/pkg/util/wait.loopConditionUntilContext.func2\n\t/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.27.4/pkg/util/wait/loop.go:73\nk8s.io/apimachinery/pkg/util/wait.loopConditionUntilContext\n\t/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.27.4/pkg/util/wait/loop.go:74\nk8s.io/apimachinery/pkg/util/wait.PollUntilContextCancel\n\t/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.27.4/pkg/util/wait/poll.go:33\nsigs.k8s.io/controller-runtime/pkg/internal/source.(*Kind).Start.func1\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.15.0/pkg/internal/source/kind.go:56"}
`

### Steps to reproduce (required)
I saw this error log in the controller pod in the long-haul test cluster.

### Observed behavior (required)
Controller Pod error logs in the long-haul test cluster.

### Desired behavior (required)
No errors.

### rad Version (required)
**Reinstalling Radius version v0.27.1 to namespace: radius-system...**

### Operating system (required)
Mac Apple Chip - Cluster is on AKS

## Additional context
Not happening locally. Seeing this error on the long-haul test cluster only for now.

[AB#10358](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/10358)

**Comment by rynowak** [comment]
@ytimocin - do you know what the exact repro of this was? 

This is probably coming from the Recipe controller, and it's complaining about the `Recipe` type missing from Kubernetes. 

This could happen if the user removes the `Recipe` CRD, or if the controller starts before the CRD is fully available.

How we proceed with this issue will depend on the repro steps. If you look at the call-stack there's no Radius code on the stack, this is coming from the underlying infrastructure.

**Comment by nicolejms** [comment]
Please add repro steps and/or specifically try to repro it for more details.

**Comment by ytimocin** [comment]
I saw this in the long-haul test cluster. Let me try to reproduce and if I can I will update this issue. I understand that without reproduction steps an action can't be taken.

**Comment by shalabhms** [comment]
@ytimocin - is the issue reproducible? If so please update the issue with repro steps.

**Comment by ytimocin** [comment]
This is already fixed @shalabhms.
