### ISSUE TITLE
Migrate chart location from ACR to GHCR

### ISSUE THREAD

**Issue by youngbupark** [radius-project/radius#6801]
## Summary

When helm retrieves the chart from GHCR, it always uses local docker credential to authenticate ghcr.io even for public repos. So if the credential is expired or invalid, it will return 403 Forbidden error. To mitigate this issue, we can override the authorization header to inject anonmous token (here is the PR #6799), but this way is just workaround solution. So it is better to show users the proper message to fix the credential problem. 

 This is to migrate chart location from ACR to GHCR:
- [ ] Revert this commit to reuse the old code - https://github.com/radius-project/radius/commit/6a4c73049d254abd64e39efe845465d088cc99bb
- [ ] When pull.Run returns 401 or 403, show the message to update ghcr.io credential or logout the ghcr.io

[AB#10416](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/10416)

**Comment by nicolejms** [comment]
We need to figure out how to do anonymous pull on GHCR. If user has expired credential, then need to update error message and ask user to refresh their creds.

**Comment by rynowak** [comment]
Did we try overriding the authorizer? https://github.com/helm/helm/blob/main/pkg/registry/client.go#L83

It looks like we could configure this so that it ignores the users docker credentials.

**Comment by youngbupark** [comment]
> Did we try overriding the authorizer? https://github.com/helm/helm/blob/main/pkg/registry/client.go#L83
> 
> 
> 
> It looks like we could configure this so that it ignores the users docker credentials. 

I tried but no way to set authorizer. The only way is using custom client with transport See #6799

**Comment by rynowak** [comment]
I double-checked this and could confirm it. There's no way to set the registry authorizer from options.

**Comment by rynowak** [comment]
Here's someone else asking for the same feature back in June: https://github.com/helm/helm/issues/12144 It was closed as stale without any fixes submitted.

**Comment by rynowak** [comment]
https://github.com/helm/helm/issues/12584

**Comment by kachawla** [comment]
Removing triage label to bring it back up for discussion, since this is blocking part of https://github.com/radius-project/radius/issues/7309

**Comment by willdavsmith** [comment]
We can print a good error message and return the 403
