### ISSUE TITLE
`'items[default]' has invalid keys: defaultapplication` error when running `rad env list`, `rad app list`, `rad init`...

### ISSUE THREAD

**Issue by ytimocin** [radius-project/radius#6838]
### Steps to reproduce (required)
1. Download latest (edge) **rad** on a fresh cluster. I did this by running `make install` on the latest main and double-checked the commit ids.
2. Run `rad env list`, `rad app list`, `rad group list`, `rad workspace list`, `rad init`... and see that you get the `'items[default]' has invalid keys: defaultapplication` error

### Observed behavior (required)
1. Can't run any command other than `rad install kubernetes`.

### Desired behavior (required)
Commands to run properly and as expected.

### Workaround (optional)
Not yet.

### rad Version (required)
RELEASE   VERSION                  BICEP     COMMIT
edge      v0.27.0-rc1-31-g2692767  0.27.1    26927674de3943c67b48dffe29f7c79e975f24ce

### Operating system (required)
macOS Sonoma 14.1.1 - Apple Chip

## Additional context
![image](https://github.com/radius-project/radius/assets/5220939/c65acd02-1259-43c4-80d2-d172a07d4f34)

[AB#10465](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/10465)

**Comment by ytimocin** [comment]
I saw that I had `defaultapplication` in my ~/.rad/config.yaml.

![image](https://github.com/radius-project/radius/assets/5220939/fba7e847-b149-4a91-a866-87b489d35d19)

When I removed it, things started to work. cc/ @rynowak

**Comment by gpltaylor** [comment]
@rynowak should this be closed. This sounds like a unique event (a  configuration miss-match) and something most people won't experience in the wild. With hindsight the error is self obvious.

**Comment by rynowak** [comment]
Great, I agree. We removed this field from the configuration. Closing
