### ISSUE TITLE
Better error message needed for the environment cloud provider configuration

### ISSUE THREAD

**Issue by ytimocin** [radius-project/radius#6861]
## Bug information

Getting this error while deploying:
```
{
"code": "AuthorizationFailed",
"message": "The client 'f96424a0-61a3-4fdf-814e-b15aff634321' with object id 'f96424a0-61a3-4fdf-814e-b15aff634321' does not have authorization to perform action 'Microsoft.ServiceBus/namespaces/write' over scope '/providers/Microsoft.ServiceBus/namespaces/testservicebusnamespace' or the scope is invalid. If access was recently granted, please refresh your credentials.",
"target": "/providers/Microsoft.ServiceBus/namespaces/testservicebusnamespace"
}
```
This is basically an environment that are missing cloud provider configuration. This needs to be told to the Radius user/operator with a more clear message.

### Steps to reproduce (required)
1. Create an environment without cloud provider configuration.
2. Deploy a bicep file that has cloud resources (like Azure Cosmos DB)
3. See the error message.

### Observed behavior (required)
Error message not being clear.

### Desired behavior (required)
Error message should state that a cloud provider needs to be configured.

### rad Version (required)
RELEASE   VERSION   BICEP     COMMIT
0.27.1    v0.27.1   0.27.1    a0fa10b71c2517934cbea90ddb87486f55652f82

### Operating system (required)
macOS, Sonoma 14.1.1, Apple Chip

## Additional context
Discussion on Discord: https://discord.com/channels/1113519723347456110/1176534953345957888/1176534953345957888.

[AB#10546](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/10546)

**Comment by willtsai** [comment]
The root cause of this is missing configuration for the Azure Scope as a part of the environment, thus the error message should indicate as such. Because the scope is missing, we're sending ARM a request something the use didn't intend, hence the authorization error being returned from Azure.

**Comment by willtsai** [comment]
@ckansara16 - i believe this one might have the same root cause as #7658 which @vishwahiremat is working on currently in https://github.com/radius-project/radius/pull/8006 -- the two of you should sync up on the fix and validating the solution!

**Comment by ckansara16** [comment]
Hello @vishwahiremat - i have reviewed #8006 . its same issue which i have started. if yes than we can close this. let me know if you need additional fix.

**Comment by willtsai** [comment]
closing as this is a confirmed duplicate of https://github.com/radius-project/radius/issues/7658

**Comment by willtsai** [comment]
Thanks @ckansara16! If you're looking for similar issues to take on, might I suggest doing some investigation into https://github.com/radius-project/radius/issues/6302 as I think it might be a separate but related issue with ambiguous errors
