### ISSUE TITLE
On-call engineer needs repo push permissions for release

### ISSUE THREAD

**Issue by willdavsmith** [radius-project/radius#6867]
## Engineering Improvement

In order to do the release, the on-call engineer should have push permissions to the repos in order to run workflows and cherry-pick fixes.

[AB#10569](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/10569)

**Comment by shalabhms** [comment]
triage: need to update the release process doc to provide permission to push to the repo.

**Comment by nicolejms** [comment]
work has been completed - there is now an on-call team with write permissions
