### ISSUE TITLE
error seen in application-rp logs

### ISSUE THREAD

**Issue by vinayada1** [radius-project/radius#6868]
### Steps to reproduce (required)
Check functional test run application-rp logs for shared tests (Example: https://github.com/radius-project/radius/actions/runs/7016117727, https://github.com/radius-project/radius/actions/runs/7018875855)

### Observed behavior (required)
{"severity":"dpanic","timestamp":"2023-11-28T12:48:44.998Z","name":"radius.radiusasyncworker","caller":"driver/terraform.go:310","message":"odd number of arguments passed as key-value pairs for logging","serviceName":"radius","version":"edge","hostName":"applications-rp-7bb84bfd68-rwnbt","resourceId":"/planes/radius/local/resourcegroups/kind-radius/providers/Applications.Core/extenders/corerp-resources-terraform-azstorage","operationId":"b542cea1-86e7-4d8a-b717-067255324b51","operationType":"APPLICATIONS.CORE/EXTENDERS|PUT","dequeueCount":1,"traceId":"4766c7114b264a5c5ad4be4ac908374f","spanId":"846f8ebb9f4c1905","ignored key":"https://blobgxuiibis3gvwy.blob.core.windows.net/test-container/test-blob","stacktrace":"github.com/radius-project/radius/pkg/recipes/driver.(*terraformDriver).getDeployedOutputResources\n\t/home/runner/work/radius/radius/pkg/recipes/driver/terraform.go:310\ngithub.com/radius-project/radius/pkg/recipes/driver.(*terraformDriver).getDeployedOutputResources\n\t/home/runner/work/radius/radius/pkg/recipes/driver/terraform.go:332\ngithub.com/radius-project/radius/pkg/recipes/driver.(*terraformDriver).prepareRecipeResponse\n\t/home/runner/work/radius/radius/pkg/recipes/driver/terraform.go:163\ngithub.com/radius-project/radius/pkg/recipes/driver.(*terraformDriver).Execute\n\t/home/runner/work/radius/radius/pkg/recipes/driver/terraform.go:103\ngithub.com/radius-project/radius/pkg/recipes/engine.(*engine).executeCore\n\t/home/runner/work/radius/radius/pkg/recipes/engine/engine.go:84\ngithub.com/radius-project/radius/pkg/recipes/engine.(*engine).Execute\n\t/home/runner/work/radius/radius/pkg/recipes/engine/engine.go:56\ngithub.com/radius-project/radius/pkg/portableresources/backend/controller.(*CreateOrUpdateResource[...]).executeRecipeIfNeeded\n\t/home/runner/work/radius/radius/pkg/portableresources/backend/controller/createorupdateresource.go:173\ngithub.com/radius-project/radius/pkg/portableresources/backend/controller.(*CreateOrUpdateResource[...]).Run\n\t/home/runner/work/radius/radius/pkg/portableresources/backend/controller/createorupdateresource.go:97\ngithub.com/radius-project/radius/pkg/armrpc/asyncoperation/worker.(*AsyncRequestProcessWorker).runOperation.func1\n\t/home/runner/work/radius/radius/pkg/armrpc/asyncoperation/worker/worker.go:254"}
{"severity":"info","timestamp":"2023-11-28T12:48:44.998Z","name":"radius.radiusasyncworker","caller":"driver/terraform.go:310","message":"Resource ID %s does not represent ARM resource and is not added to recipe output","serviceName":"radius","version":"edge","hostName":"applications-rp-7bb84bfd68-rwnbt","resourceId":"/planes/radius/local/resourcegroups/kind-radius/providers/Applications.Core/extenders/corerp-resources-terraform-azstorage","operationId":"b542cea1-86e7-4d8a-b717-067255324b51","operationType":"APPLICATIONS.CORE/EXTENDERS|PUT","dequeueCount":1,"traceId":"4766c7114b264a5c5ad4be4ac908374f","spanId":"846f8ebb9f4c1905"}
{"severity":"dpanic","timestamp":"2023-11-28T12:48:44.998Z","name":"radius.radiusasyncworker","caller":"driver/terraform.go:310","message":"odd number of arguments passed as key-value pairs for logging","serviceName":"radius","version":"edge","hostName":"applications-rp-7bb84bfd68-rwnbt","resourceId":"/planes/radius/local/resourcegroups/kind-radius/providers/Applications.Core/extenders/corerp-resources-terraform-azstorage","operationId":"b542cea1-86e7-4d8a-b717-067255324b51","operationType":"APPLICATIONS.CORE/EXTENDERS|PUT","dequeueCount":1,"traceId":"4766c7114b264a5c5ad4be4ac908374f","spanId":"846f8ebb9f4c1905","ignored key":"https://blobgxuiibis3gvwy.blob.core.windows.net/test-container","stacktrace":"github.com/radius-project/radius/pkg/recipes/driver.(*terraformDriver).getDeployedOutputResources\n\t/home/runner/work/radius/radius/pkg/recipes/driver/terraform.go:310\ngithub.com/radius-project/radius/pkg/recipes/driver.(*terraformDriver).getDeployedOutputResources\n\t/home/runner/work/radius/radius/pkg/recipes/driver/terraform.go:332\ngithub.com/radius-project/radius/pkg/recipes/driver.(*terraformDriver).prepareRecipeResponse\n\t/home/runner/work/radius/radius/pkg/recipes/driver/terraform.go:163\ngithub.com/radius-project/radius/pkg/recipes/driver.(*terraformDriver).Execute\n\t/home/runner/work/radius/radius/pkg/recipes/driver/terraform.go:103\ngithub.com/radius-project/radius/pkg/recipes/engine.(*engine).executeCore\n\t/home/runner/work/radius/radius/pkg/recipes/engine/engine.go:84\ngithub.com/radius-project/radius/pkg/recipes/engine.(*engine).Execute\n\t/home/runner/work/radius/radius/pkg/recipes/engine/engine.go:56\ngithub.com/radius-project/radius/pkg/portableresources/backend/controller.(*CreateOrUpdateResource[...]).executeRecipeIfNeeded\n\t/home/runner/work/radius/radius/pkg/portableresources/backend/controller/createorupdateresource.go:173\ngithub.com/radius-project/radius/pkg/portableresources/backend/controller.(*CreateOrUpdateResource[...]).Run\n\t/home/runner/work/radius/radius/pkg/portableresources/backend/controller/createorupdateresource.go:97\ngithub.com/radius-project/radius/pkg/armrpc/asyncoperation/worker.(*AsyncRequestProcessWorker).runOperation.func1\n\t/home/runner/work/radius/radius/pkg/armrpc/asyncoperation/worker/worker.go:254"}

### Desired behavior (required)
Do not expect to see this

## Additional context

[AB#10571](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/10571)

**Comment by kachawla** [comment]
Thanks for fixing this @ytimocin!
