### ISSUE TITLE
Panic when deploying application

### ISSUE THREAD

**Issue by AaronCrawfis** [radius-project/radius#6882]
### Steps to reproduce (required)

1. Create a new k3s cluster with `k3d cluster create`
2. Initialize Radius 0.27 with `rad init`
3. Create a new file named `app.bicep` with the following contents:

```bicep
import radius as radius

resource app 'Applications.Core/applications@2023-10-01-preview' = {
  name: 'myapp'
}
```
4. Deploy the app with `rad deploy ./app.bicep`
5. Get error message (below)

### Observed behavior (required)

```
rad deploy .\app.bicep
Building .\app.bicep...
Deploying template '.\app.bicep' into environment 'default' from workspace 'default'...

Deployment In Progress...

..                   myapp           Applications.Core/applications
Error: {
  "code": "DeploymentFailed",
  "message": "At least one resource deployment operation failed. Please see the details for the specific operation that failed.",
  "target": "/planes/radius/local/resourceGroups/default/providers/Microsoft.Resources/deployments/rad-deploy-d680eed6-5e9d-4892-9beb-7e8c3d231bb9",
  "details": [
    {
      "code": "Internal",
      "message": "unexpected error: runtime error: invalid memory address or nil pointer dereference",
      "target": "/planes/radius/local/resourceGroups/default/providers/Applications.Core/applications/myapp"
    }
  ]
}

TraceId:  0b5c759598282c25d75c4b9a65e12c0b
```

### Desired behavior (required)

I expect that my application can deploy correctly

### Workaround (optional)

None

### Operating system (required)

Windows 11, x64

[AB#10593](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/10593)

**Comment by AaronCrawfis** [comment]
[bicep-logs.txt](https://github.com/radius-project/radius/files/13506651/bicep-logs.txt)
[rp-logs.txt](https://github.com/radius-project/radius/files/13506652/rp-logs.txt)
[ucp-logs.txt](https://github.com/radius-project/radius/files/13506653/ucp-logs.txt)

**Comment by rynowak** [comment]
I'm guessing that this repros when `properties` is omitted.

**Comment by AaronCrawfis** [comment]
> I'm guessing that this repros when `properties` is omitted.

Yep that fixed it. We should make `properties.environment` a required field
