### ISSUE TITLE
Investigate pulling the RC tagged version of bicep during release verification

### ISSUE THREAD

**Issue by sk593** [radius-project/radius#6897]
### Area for Improvement (required)

This issue is to investigate pulling the RC tagged version of bicep during the release verification workflow or somewhere in the release process. 

### Observed behavior (required)
We ran into an issue with the 0.27 release process where the samples verification workflow failed while downloading bicep but was not caught in any other workflows. This is because the samples repo is the only place that tests pulling an RC tagged version of bicep here: https://github.com/radius-project/samples/blob/a420f9e02151240905ceb63c0da881f268d5d527/.github/workflows/test.yaml#L189

We found that the RC tagged version of bicep was not getting uploaded and had to create a fix during the 0.27 release process. 

### Desired behavior (required)

Ideally, we would have caught this download failure earlier in the release process, before we ran the samples verification workflow. We have a release verification workflow that runs once we create an RC version of the release, but there's no step to test bicep downloads, see here: https://github.com/radius-project/radius/blob/main/.github/scripts/release-verification.sh

### Proposed Fix (optional)

We'd like to investigate if we can test bicep downloads earlier in the release process so that we catch possible errors sooner. 

## Additional context

[AB#10635](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/10635)

**Comment by nicolejms** [comment]
Removing important since we will need to revisit how we decide what version of the public bicep release we will be using each release.
