### ISSUE TITLE
[Application Graph API] Endpoint in control plane

### ISSUE THREAD

**Issue by willtsai** [radius-project/radius#6900]
## Overview of feature request

As a Radius user, I am able to make API requests against an endpoint that is deployed and served by the Radius Control Plane to query for the “nodes” and “edges” that make up my application graph. These include the comprehensive set of core resources (environments, applications, containers, gateways, extenders, secret stores, volumes, etc.) and portable resources (datastore, messaging, dapr, etc.), as well as the connections and routes between the resources. As a result, I’m able to access the application graph data so that I may build an understanding or visualization of the resources that make up my application and architecture.

## Acceptance criteria

- Users can make API requests against a Radius control plane endpoint and/or using `rad app connections` to query for application graph data.
- Comprehensive documentation that includes API references and how-to guides.

## Additional context

related to #6901 

relevant design: https://github.com/radius-project/design-notes/blob/main/resources/2023-10-app-graph.md

[AB#10639](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/10639)

**Comment by nithyatsu** [comment]
> Is this done? @nithyatsu did we ever complete the work in the CLI to use this new API?

Not yet, we have the ticket https://github.com/radius-project/radius/issues/6631 that suggests having a discussion on performance before implementing it..

**Comment by nithyatsu** [comment]
implemented cli connections using graph API. ref. https://github.com/radius-project/radius/issues/6631

**Comment by nithyatsu** [comment]
reopened to work with @willtsai and make sure the documentation is covered.
