### ISSUE TITLE
Easier start for Radius CLI contributors

### ISSUE THREAD

**Issue by lechnerc77** [radius-project/radius#6904]
### Area for Improvement (required)

Developing contributions for the Radius CLI

### Observed behavior (required)

When making contributions or working on bugs the developer needs to setup the necessary environment manually. 
Debugging the CLI from scratch might also be a barrier for new contributors

### Desired behavior (required)

It would be an improvment if the following parts exists:

- devcontainer configuration containing the basic setup for working with the CLI
- a debug launch configuration that allows the contributor to directly exectute a command of the CLI

### Proposed Fix (optional)

- Add a new devcontainer configuration
- Enhance the `launch.json` with a debug configuration targeting the CLI

### rad Version (required)

n/a as working with local build when contributing

### Operating system (required)

Linux (devcontainer)

## Additional context

n/a

[AB#10643](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/10643)

**Comment by vinayada1** [comment]
Thanks @lechnerc77 for submitting this issue. We will look into this shortly.
