### ISSUE TITLE
Radius CLI as Devcontainer feature

### ISSUE THREAD

**Issue by lechnerc77** [radius-project/radius#6906]
## Overview of feature request

Proivde the Radius CLI as a devcontainer feature (see <https://containers.dev/features>) to make the provisioning of a devcontainer environment easier. 

## Acceptance criteria

The radius CLI is available as devcontainer feature in the official and community-supported devcontainer feature page (<<https://containers.dev/features>>) and can be used within dev containers via the `feature` section

## Additional context

Happy to suport on this topic

[AB#10644](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/10644)

**Comment by lechnerc77** [comment]
The repository I referenced already anticipated the move into your repository. Expect a first PR soon :-)

**Comment by lechnerc77** [comment]
@rynowak : here is the first version of the PR https://github.com/radius-project/radius/pull/6930. Looking forward to your feedback

**Comment by rynowak** [comment]
Thanks @lechnerc77
