### ISSUE TITLE
Support for Private Terraform Modules

### ISSUE THREAD

**Issue by rynowak** [radius-project/radius#6911]
## Overview of feature request

Radius can work with publicly-hosted Terraform modules across a few different module sources. We don't support working with privately-hosted Terraform modules, and there's no way to configure authentication.

This is important because organizations write their own Terraform modules and store them in privately-accessible sources. In order for us to support serious use, we need to enable private sources.

The challenge is that each module source has its own authentication mechanism with its own style of configuration. For example the `git` module source relies on the environment hosting Terraform to provide the credentials. 

**For right now the set of required sources is TBD.**

## Acceptance criteria

Other than the "glue" to wire up credentials, the Terraform Recipe driver should behave the same way for a private module. Given the correct configuration of credentials, the Terraform driver should behave the same for a public vs private module.

- Radius API allows users to register credentials for some set of Terraform module sources.
- TBD set of Terraform module sources are supported.
- Documentation updated.

## Additional context

It may be helpful to pair this with the work to isolate the Terraform driver in its own container. Some of the source configuration makes changes to the execution environment (for example logging into git). 

[AB#10652](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/10652)

**Comment by rynowak** [comment]
Triage Team: creating this issue to track roadmap work.

**Comment by AaronCrawfis** [comment]
reopening as functional tests and docs still need to be created
