### ISSUE TITLE
Recipe support for private Bicep registries

### ISSUE THREAD

**Issue by AaronCrawfis** [radius-project/radius#6917]
## Current state

Today we allow OCI registries with anonymous pull to be used as Bicep registries for Recipes. For example, `ghcr.io/radius-project/recipes/local-dev/rediscaches:latest` is a public Recipe Bicep module: https://github.com/radius-project/recipes/pkgs/container/recipes%2Flocal-dev%2Frediscaches

## Desired state

We want to enable users to be able to use private OCI registries that are not open to the public. For example, an ACR or GHCR registry could be locked down to only certain users or accounts.

## Acceptance criteria

- [x] A user can create an OCI registry, such as an Azure Container Registry, that is private and can only be pulled from by allowed users/accounts
- [x] Recipes can be pushed to this OCI registry via `rad bicep publish`, after the user logs into the OCI registry via the registries login mechanism (`az acr login` for example).
- [x] The private Recipe can be added to an environment's list of Recipes
- [ ] A user can configure credentials for the OCI registry
- [ ] Radius uses the credentials to fetch Recipes
- [ ] If credentials are invalid for the registry, an anonymous pull is attempted. This prevents a user from registering credentials for `ghcr.io/myaccount` and then public recipes for `ghcr.io/radius-project` can no longer be pulled.
- [ ] Users can list configured credentials and view the username, but not the password
- [ ] Users update credentials to roll them when they are expired or need to be replaced
- [ ] Users can remove credentials for a specific OCI registry
- [ ] Nested Bicep modules can leverage the same set of credentials

[AB#10666](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/10666)

**Comment by AaronCrawfis** [comment]
Similar to #6911

**Comment by shalabhms** [comment]
Triaged: similar parity #6911
