### ISSUE TITLE
[Application graph]- Minor additions to API

### ISSUE THREAD

**Issue by nithyatsu** [radius-project/radius#6937]
Enhance Application Graph API
- to support HTTPRoute-less connection identification and display
- to add a URL for cloud resources (this was present earlier on cli side of functionality)

[AB#10710](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/10710)

**Comment by rynowak** [comment]
These seem like good ideas. We definitely want to support visualizing connections for DNS-based service discovery.

I think the browsable URLs seems less valuable for an API client. Nice to have but less valuable than the connection info.
