### ISSUE TITLE
Review and Remove or Enable Skipped Functional Test: `Test_AWSRedeployWithCreateAndWriteOnlyPropertyUpdate`

### ISSUE THREAD

**Issue by kachawla** [radius-project/radius#6949]
### Problem
It appears that the test [Test_AWSRedeployWithCreateAndWriteOnlyPropertyUpdate](https://github.com/radius-project/radius/blob/main/test/functional/shared/mechanics/aws_mechanics_test.go#L96) was added over a year ago as a part of [commit](https://github.com/radius-project/radius/commit/b22a175ab19a68111a2a83b41c566016e1e07f23), but it has never been enabled. The criteria for re-enabling the test are unclear from the comment in the commit message.

### Next Steps
1. Review the test [Test_AWSRedeployWithCreateAndWriteOnlyPropertyUpdate](https://github.com/radius-project/radius/blob/main/test/functional/shared/mechanics/aws_mechanics_test.go#L96) to understand its purpose and what scenarios it validates.
2. Determine if the scenario being tested is still supported and relevant.
3. Based on the evaluation above, either enable the test if it's relevant or remove it if it's no longer needed.

[AB#10754](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/10754)

**Comment by shalabhms** [comment]
@willdavsmith - is this test still relevant ?

**Comment by willdavsmith** [comment]
> @willdavsmith - is this test still relevant ?

Yes, but we cannot enable it until we have support non-idempotent AWS resources. These tests never ran successfully. We should link this issue https://github.com/radius-project/radius/issues/6227 in the test or remove it

**Comment by kachawla** [comment]
> > @willdavsmith - is this test still relevant ?
> 
> Yes, but we cannot enable it until we have support non-idempotent AWS resources. These tests never ran successfully. We should link this issue #6227 in the test or remove it

I think we should remove this test until the feature is implemented. Adding this and other feature specific tests should be a part of the overall feature plan.

**Comment by shalabhms** [comment]
triage:  decided to remove the test.  The test will be added once the feature is added.
