### ISSUE TITLE
Backstage plugins for Recipes, Resource Provisioning, etc.

### ISSUE THREAD

**Issue by willtsai** [radius-project/radius#6963]
## Overview of feature request

Beyond the Application Graph API and simple dashboard via Backstage plugin, we would like to deliver additional Dashboard capabilities. These may include other Radius Backstage plugins for Recipes, Resource Provisioning, etc.

## Acceptance criteria

Either new Backstage plugins or enhancement of existing Radius plugins to bring features like Recipes, Resource Provisioning, Deployment, etc. to Backstage.

## Additional context

[AB#10786](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/10786)

**Comment by rynowak** [comment]
What's the intersection between this and https://backstage.io/docs/features/software-templates/ ? Backstage already has a mechanism for "deploying stuff" that should be able to leverage. (We already know some folks using it for Radius).
