### ISSUE TITLE
Serverless on Radius: ACI integration

### ISSUE THREAD

**Issue by willtsai** [radius-project/radius#6964]
## Overview of feature request

Some of the most commonly asked questions from both customer sessions and Discord discussions are related to our plans to build integrations with Serverless offerings. Specifically, the desire is to integrate Radius with Azure Container Instances (ACI) as the first unopinionated Serverless offering on Radius.

## Acceptance criteria

Support is provided for ACI resources on Radius.

## Additional context

[AB#10790](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/10790)

**Comment by rynowak** [comment]
@willtsai - suggestion: can you update the title to say "Serverless container platform"?

When we talk about this topic there's often confusion about the meaning of the term:

- Serverless => on-demand and elastic scale without management overhead. 
- Serverless => event-driven programming model, or function-as-a-service runtime.

Many users are familiar with platforms like AWS Lambda which satisfy **both** definitions. 

The [wikipedia definition](https://en.wikipedia.org/wiki/Serverless_computing) is pretty good. 

--- 

I hope we can make it clear that **this work item** is about using `Applications.Core/containers` and our other cloud-native primitives to target Azure ACI or, AWS ECS, or other **unopinionated** container runtimes. 

Opinionated runtimes like AWS Lambda are also a really interesting topic for Radius, but that's not what this work item tracks 😉

**Comment by gpltaylor** [comment]
Implementing ACI come with some questions. As the Contol Plan is isolated, some K8s functionality is missing.
I fear that users of Radius would expect K8s style control whilst using ACIs as their container host of choice.

This means that the following MAY require custom operators to keep everything in sync...

* Service/ingress
* DNS Resolution
* VPN with DNS
* Mounted Storage

Whilst deployment of ACI using Radius is a "know know" and uncomplex to implement, keeping it running and syncronosed with other resources is a challenge. 

Maybe start with a simple Public ACI with a Domain Name and a backend API/Cache using DAPR. Public ACI keep the IP and DNS in sync and reduces a lot of new issues :)

**Comment by willtsai** [comment]
Will track this in a separate space and share once available, closing this issue for now.

**Comment by AaronCrawfis** [comment]
> Will track this in a separate space and share once available, closing this issue for now.

Link to new tracking item: https://github.com/orgs/radius-project/projects/8/views/1?pane=issue&itemId=47750916
