### ISSUE TITLE
Issue reporting - usage of issue forms

### ISSUE THREAD

**Issue by lechnerc77** [radius-project/radius#6981]
### Area for Improvement (required)

The area that could be improved are the GitHub issues namely switching from the markdown templates to the form-based templates.

### Observed behavior (required)

The repository contains markdown temaplates for the GitHub issues. This already supports the reporting as a basic structure is available. However, the layout could be improved and the validations (mandatory vs. optional areas) are not possible

### Desired behavior (required)

Usage of form-based templates fo the issue ([link](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms)) that can improve the above mentioned areas and give more options for future improvements (like checkboxes or drop downdown menus

### Proposed Fix (optional)

Transfer issue templates form markdown into form/yaml-based templates

### rad Version (required)

n/a

### Operating system (required)

n/a

## Additional context

Also beeing a beta feature, I am using it since the public beta phase and did not face any issues since then. 

### Layout examples

Here are some screenshot how the new layout would look like. The first selection screen would remain unchanged:

![overview](https://github.com/radius-project/radius/assets/22294087/1542b51b-59df-4112-bc56-f259714f1f53)

After selecting one the types the form-based templates is displayed. 

#### Bug template
Here is an example of the layout for bugs with a more concise strcuture for the reporter as well as validation i.e., obligatory fields are marked:

![bug-form](https://github.com/radius-project/radius/assets/22294087/1f5b8e4e-dce0-42bd-8e6e-5a42e390a2cf)

There is also the option to have additional features like checkboxes:

![bug-form2](https://github.com/radius-project/radius/assets/22294087/4545afb4-52ea-480f-9f0f-4f7996bf074a)

#### Engineering improvement

Example for the engineering improvement (upper area):

![engineering_1](https://github.com/radius-project/radius/assets/22294087/3cec49e9-565a-40c9-b7bd-9312af59e2a0)

#### Feature request

Example for feature request:

![feature](https://github.com/radius-project/radius/assets/22294087/7030afc3-084b-484e-b089-a58fffe1e6aa)

### Testing

You can test it in the repository <https://github.com/lechnerc77/ghaction-testing/issues/new/choose> to see the validation options etc.

[AB#10805](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/10805)

**Comment by rynowak** [comment]
I think this is a neat idea, and when we started the project this feature didn't exist yet. I want to make sure we get input from the folks that review incoming issues before we make any decisions.

My only concern is that I don't want opening an issue to **feel** complicated. I would be disappointed if community members decide against opening issues because it's hard. My bias would be towards fewer fields and fewer required fields.

**Comment by lechnerc77** [comment]
Fully agree that the the barrier should be low without sacrificing essential input for maintainers. The current proposal is a 1:1 migration of the existing templates. Maybe this issue and PR can also be used to consolidate the layout of the issues and provide better guidance (like hints and placeholders what to fill in the sections). 

I took a look at the helm issue template, but in my opinion I woul dhave no idea how to best provide the information with this minimalistic template. I personally prefer the questions the radius templates have (maybe some parts can be made optional), as they give better guidance.

Happy to hear feedback to improve the provided PR assuming that you want to stick to forms.

**Comment by rynowak** [comment]
> The current proposal is a 1:1 migration of the existing templates. Maybe this issue and PR can also be used to consolidate the layout of the issues and provide better guidance (like hints and placeholders what to fill in the sections).

I saw that 👍 thanks!

**Comment by AaronCrawfis** [comment]
I've been a big fan of Issue Forms since I first came across them a few months ago. I agree that we should make it easy to fill out and not deter people from filling it out. An easy solution could be to make only 1-2 items required the rest are best effort (with the hope that they're filled out. For example, operating system).

+1 from me for adding this!

**Comment by lechnerc77** [comment]
@AaronCrawfis I changed the settings for required fields according to your feedback in PR #6982 .

The feature request is down to 1 required field, the other ones (bug and engineering improvement) are down to 3 required irtems, that makes sense from my perspective and give the maintainers a fair starting ground for the issue analysis without making it too difficult for users to fill in the information. 
If you would like to see further changes, just let me know
