### ISSUE TITLE
Panic while getting application graph

### ISSUE THREAD

**Issue by vinayada1** [radius-project/radius#7004]
### Steps to reproduce (required)
1. Ran Test_GatewayDNS in our test suite without the test cleanup part
2. Try to get rad app graph

### Observed behavior (required)
~/temp % rad app graph -a corerp-resources-gateway-dns
Error: {
  "code": "Internal",
  "message": "unexpected error: runtime error: invalid memory address or nil pointer dereference"
}

TraceId:  930261052ed8384c2c7dce7ceacddafb

StackTrace in the logs:-
{"severity":"error","timestamp":"2024-01-09T19:20:16.590Z","name":"radius.radiusapi","caller":"middleware/recoverer.go:37","message":"recovering from panic","serviceName":"radius","version":"0.29","hostName":"applications-rp-697cdf6b-bh7kw","traceId":"3b25ec1067ff7cde66dbe5bba2b97ad8","spanId":"f86e22a25d4c7e35","error":"recovering from panic runtime error: invalid memory address or nil pointer dereference: goroutine 2096 [running]:\nruntime/debug.Stack()\n\t/opt/hostedtoolcache/go/1.21.5/x64/src/runtime/debug/stack.go:24 +0x5e\ngithub.com/radius-project/radius/pkg/middleware.Recoverer.func1.1()\n\t/home/runner/work/radius/radius/pkg/middleware/recoverer.go:36 +0xa5\npanic({0x2362e20?, 0x40b3360?})\n\t/opt/hostedtoolcache/go/1.21.5/x64/src/runtime/panic.go:914 +0x21f\ngithub.com/radius-project/radius/pkg/corerp/frontend/controller/applications.computeGraph({0xc002ee77a0?, 0x5c?}, {0xc002c1f290?, 0x3, 0x2?}, {0x4123ea0?, 0x0, 0x1?})\n\t/home/runner/work/radius/radius/pkg/corerp/frontend/controller/applications/graph_util.go:303 +0x11bb\ngithub.com/radius-project/radius/pkg/corerp/frontend/controller/applications.(*GetGraph).Run(0xc00140a9a0, {0x2be3ab8, 0xc00268d6b0}, {0x0?, 0x0?}, 0x0?)\n\t/home/runner/work/radius/radius/pkg/corerp/frontend/controller/applications/getgraph.go:85 +0x405\ngithub.com/radius-project/radius/pkg/armrpc/frontend/server.RegisterHandler.HandlerForController.func1({0x2bdeaa0, 0xc0034fae40}, 0x4?)\n\t/home/runner/work/radius/radius/pkg/armrpc/frontend/server/handler.go:114 +0x11c\nnet/http.HandlerFunc.ServeHTTP(0xc00145c0a0?, {0x2bdeaa0?, 0xc0034fae40?}, 0xc002edd5c0?)\n\t/opt/hostedtoolcache/go/1.21.5/x64/src/net/http/server.go:2136 +0x29\ngithub.com/go-chi/chi/v5.(*ChainHandler).ServeHTTP(0x233bd40?, {0x2bdeaa0?, 0xc0034fae40?}, 0xc00178a500?)\n\t/home/runner/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.10/chain.go:31 +0x26\ngithub.com/go-chi/chi/v5.(*Mux).routeHTTP(0xc000880d80, {0x2bdeaa0, 0xc0034fae40}, 0xc002ee3a00)\n\t/home/runner/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.10/mux.go:444 +0x2b4\nnet/http.HandlerFunc.ServeHTTP(0x8?, {0x2bdeaa0?, 0xc0034fae40?}, 0x4103c5?)\n\t/opt/hostedtoolcache/go/1.21.5/x64/src/net/http/server.go:2136 +0x29\ngithub.com/radius-project/radius/pkg/armrpc/builder.NewOpenAPIValidator.APIValidator.func1.1({0x2bdeaa0, 0xc0034fae40}, 0xc002ee3a00)\n\t/home/runner/work/radius/radius/pkg/validator/apivalidator.go:72 +0x3c5\nnet/http.HandlerFunc.ServeHTTP(0xc0041eef70?, {0x2bdeaa0?, 0xc0034fae40?}, 0xc0041eef50?)\n\t/opt/hostedtoolcache/go/1.21.5/x64/src/net/http/server.go:2136 +0x29\ngithub.com/go-chi/chi/v5.(*Mux).ServeHTTP(0xc000880d80, {0x2bdeaa0, 0xc0034fae40}, 0xc002ee3a00)\n\t/home/runner/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.10/mux.go:73 +0x356\ngithub.com/go-chi/chi/v5.(*Mux).Mount.func1({0x2bdeaa0, 0xc0034fae40}, 0xc002ee3a00)\n\t/home/runner/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.10/mux.go:316 +0x1bb\nnet/http.HandlerFunc.ServeHTTP(0x233bd40?, {0x2bdeaa0?, 0xc0034fae40?}, 0xc002d94280?)\n\t/opt/hostedtoolcache/go/1.21.5/x64/src/net/http/server.go:2136 +0x29\ngithub.com/go-chi/chi/v5.(*Mux).routeHTTP(0xc0004a2300, {0x2bdeaa0, 0xc0034fae40}, 0xc002ee3a00)\n\t/home/runner/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.10/mux.go:444 +0x2b4\nnet/http.HandlerFunc.ServeHTTP(0xc002ee3900?, {0x2bdeaa0?, 0xc0034fae40?}, 0xc0002b2b90?)\n\t/opt/hostedtoolcache/go/1.21.5/x64/src/net/http/server.go:2136 +0x29\ngithub.com/radius-project/radius/pkg/armrpc/frontend/server.New.ARMRequestCtx.func5.1({0x2bdeaa0, 0xc0034fae40}, 0x1?)\n\t/home/runner/work/radius/radius/pkg/armrpc/servicecontext/middleware.go:59 +0x1a2\nnet/http.HandlerFunc.ServeHTTP(0x2be3ab8?, {0x2bdeaa0?, 0xc0034fae40?}, 0x2?)\n\t/opt/hostedtoolcache/go/1.21.5/x64/src/net/http/server.go:2136 +0x29\ngithub.com/radius-project/radius/pkg/middleware.WithLogger.func1({0x2bdeaa0, 0xc0034fae40}, 0xc002ee3800)\n\t/home/runner/work/radius/radius/pkg/middleware/logger.go:37 +0x2ca\nnet/http.HandlerFunc.ServeHTTP(0x100?, {0x2bdeaa0?, 0xc0034fae40?}, 0x410745?)\n\t/opt/hostedtoolcache/go/1.21.5/x64/src/net/http/server.go:2136 +0x29\ngithub.com/radius-project/radius/pkg/middleware.Recoverer.func1({0x2bdeaa0?, 0xc0034fae40?}, 0x40b4201?)\n\t/home/runner/work/radius/radius/pkg/middleware/recoverer.go:50 +0x78\nnet/http.HandlerFunc.ServeHTTP(0x2be3ab8?, {0x2bdeaa0?, 0xc0034fae40?}, 0x40b42c0?)\n\t/opt/hostedtoolcache/go/1.21.5/x64/src/net/http/server.go:2136 +0x29\ngithub.com/go-chi/chi/v5.(*Mux).ServeHTTP(0xc0004a2300, {0x2bdeaa0, 0xc0034fae40}, 0xc002ee3700)\n\t/home/runner/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.10/mux.go:90 +0x315\ngithub.com/radius-project/radius/pkg/armrpc/frontend/server.New.LowercaseURLPath.func6({0x2bdeaa0, 0xc0034fae40}, 0xc002ee3700)\n\t/home/runner/work/radius/radius/pkg/middleware/lowercaseurlpath.go:42 +0x130\nnet/http.HandlerFunc.ServeHTTP(0x2be3ab8?, {0x2bdeaa0?, 0xc0034fae40?}, 0x2bb01d0?)\n\t/opt/hostedtoolcache/go/1.21.5/x64/src/net/http/server.go:2136 +0x29\ngo.opentelemetry.io/contrib/instrumentation/net/http/otelhttp.(*Handler).ServeHTTP(0xc002ea4600, {0x2bd2460?, 0xc001df5b20}, 0xc002ee3500)\n\t/home/runner/go/pkg/mod/go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp@v0.42.0/handler.go:212 +0x1204\ngithub.com/radius-project/radius/pkg/armrpc/frontend/server.New.RemoveRemoteAddr.func9({0x2bd2460?, 0xc001df5b20?}, 0xc0011c4080?)\n\t/home/runner/work/radius/radius/pkg/middleware/removeremoteaddr.go:28 +0x65\nnet/http.HandlerFunc.ServeHTTP(0x410745?, {0x2bd2460?, 0xc001df5b20?}, 0xc001df5b01?)\n\t/opt/hostedtoolcache/go/1.21.5/x64/src/net/http/server.go:2136 +0x29\nnet/http.serverHandler.ServeHTTP({0x2bc4408?}, {0x2bd2460?, 0xc001df5b20?}, 0x6?)\n\t/opt/hostedtoolcache/go/1.21.5/x64/src/net/http/server.go:2938 +0x8e\nnet/http.(*conn).serve(0xc002fd0510, {0x2be3ab8, 0xc0026c6930})\n\t/opt/hostedtoolcache/go/1.21.5/x64/src/net/http/server.go:2009 +0x5f4\ncreated by net/http.(*Server).Serve in goroutine 153\n\t/opt/hostedtoolcache/go/1.21.5/x64/src/net/http/server.go:3086 +0x5cb\n","stacktrace":"github.com/radius-project/radius/pkg/middleware.Recoverer.func1.1\n\t/home/runner/work/radius/radius/pkg/middleware/recoverer.go:37\nruntime.gopanic\n\t/opt/hostedtoolcache/go/1.21.5/x64/src/runtime/panic.go:914\nruntime.panicmem\n\t/opt/hostedtoolcache/go/1.21.5/x64/src/runtime/panic.go:261\nruntime.sigpanic\n\t/opt/hostedtoolcache/go/1.21.5/x64/src/runtime/signal_unix.go:861\ngithub.com/radius-project/radius/pkg/corerp/frontend/controller/applications.computeGraph\n\t/home/runner/work/radius/radius/pkg/corerp/frontend/controller/applications/graph_util.go:303\ngithub.com/radius-project/radius/pkg/corerp/frontend/controller/applications.(*GetGraph).Run\n\t/home/runner/work/radius/radius/pkg/corerp/frontend/controller/applications/getgraph.go:85\ngithub.com/radius-project/radius/pkg/armrpc/frontend/server.RegisterHandler.HandlerForController.func1\n\t/home/runner/work/radius/radius/pkg/armrpc/frontend/server/handler.go:114\nnet/http.HandlerFunc.ServeHTTP\n\t/opt/hostedtoolcache/go/1.21.5/x64/src/net/http/server.go:2136\ngithub.com/go-chi/chi/v5.(*ChainHandler).ServeHTTP\n\t/home/runner/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.10/chain.go:31\ngithub.com/go-chi/chi/v5.(*Mux).routeHTTP\n\t/home/runner/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.10/mux.go:444\nnet/http.HandlerFunc.ServeHTTP\n\t/opt/hostedtoolcache/go/1.21.5/x64/src/net/http/server.go:2136\ngithub.com/radius-project/radius/pkg/armrpc/builder.NewOpenAPIValidator.APIValidator.func1.1\n\t/home/runner/work/radius/radius/pkg/validator/apivalidator.go:72\nnet/http.HandlerFunc.ServeHTTP\n\t/opt/hostedtoolcache/go/1.21.5/x64/src/net/http/server.go:2136\ngithub.com/go-chi/chi/v5.(*Mux).ServeHTTP\n\t/home/runner/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.10/mux.go:73\ngithub.com/go-chi/chi/v5.(*Mux).Mount.func1\n\t/home/runner/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.10/mux.go:316\nnet/http.HandlerFunc.ServeHTTP\n\t/opt/hostedtoolcache/go/1.21.5/x64/src/net/http/server.go:2136\ngithub.com/go-chi/chi/v5.(*Mux).routeHTTP\n\t/home/runner/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.10/mux.go:444\nnet/http.HandlerFunc.ServeHTTP\n\t/opt/hostedtoolcache/go/1.21.5/x64/src/net/http/server.go:2136\ngithub.com/radius-project/radius/pkg/armrpc/frontend/server.New.ARMRequestCtx.func5.1\n\t/home/runner/work/radius/radius/pkg/armrpc/servicecontext/middleware.go:59\nnet/http.HandlerFunc.ServeHTTP\n\t/opt/hostedtoolcache/go/1.21.5/x64/src/net/http/server.go:2136\ngithub.com/radius-project/radius/pkg/middleware.WithLogger.func1\n\t/home/runner/work/radius/radius/pkg/middleware/logger.go:37\nnet/http.HandlerFunc.ServeHTTP\n\t/opt/hostedtoolcache/go/1.21.5/x64/src/net/http/server.go:2136\ngithub.com/radius-project/radius/pkg/middleware.Recoverer.func1\n\t/home/runner/work/radius/radius/pkg/middleware/recoverer.go:50\nnet/http.HandlerFunc.ServeHTTP\n\t/opt/hostedtoolcache/go/1.21.5/x64/src/net/http/server.go:2136\ngithub.com/go-chi/chi/v5.(*Mux).ServeHTTP\n\t/home/runner/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.10/mux.go:90\ngithub.com/radius-project/radius/pkg/armrpc/frontend/server.New.LowercaseURLPath.func6\n\t/home/runner/work/radius/radius/pkg/middleware/lowercaseurlpath.go:42\nnet/http.HandlerFunc.ServeHTTP\n\t/opt/hostedtoolcache/go/1.21.5/x64/src/net/http/server.go:2136\ngo.opentelemetry.io/contrib/instrumentation/net/http/otelhttp.(*Handler).ServeHTTP\n\t/home/runner/go/pkg/mod/go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp@v0.42.0/handler.go:212\ngithub.com/radius-project/radius/pkg/armrpc/frontend/server.New.RemoveRemoteAddr.func9\n\t/home/runner/work/radius/radius/pkg/middleware/removeremoteaddr.go:28\nnet/http.HandlerFunc.ServeHTTP\n\t/opt/hostedtoolcache/go/1.21.5/x64/src/net/http/server.go:2136\nnet/http.serverHandler.ServeHTTP\n\t/opt/hostedtoolcache/go/1.21.5/x64/src/net/http/server.go:2938\nnet/http.(*conn).serve\n\t/opt/hostedtoolcache/go/1.21.5/x64/src/net/http/server.go:2009"}
{"severity":"info","timestamp":"2024-01-09T19:20:16.590Z","name":"radius.radiusapi","caller":"rest/results.go:625","message":"responding with status code: 500","serviceName":"radius","version":"0.29","hostName":"applications-rp-697cdf6b-bh7kw","traceId":"3b25ec1067ff7cde66dbe5bba2b97ad8","spanId":"f86e22a25d4c7e35","statusCode":500}

### Desired behavior (required)
The code should not panic

### rad Version (required)

~/temp % rad version
RELEASE   VERSION   BICEP     COMMIT
0.29.0    v0.29.0   0.29.0    6abd7bfc3de0e748a2c34b721d95097afb6a2bba

### Operating system (required)

macOS Sonoma 14.2.1 (23C71)

## Additional context

[AB#10849](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/10849)

**Comment by nithyatsu** [comment]
@vinayada1 , this is because the appGraph API does not yet support route-less connections. https://github.com/radius-project/radius/issues/6937 logs the requirement.
