### ISSUE TITLE
Support for Terraform Submodules with Context Variables

### ISSUE THREAD

**Issue by sk593** [radius-project/radius#7005]
### Area for Improvement (required)
It seems like Terraform registries don't work with submodules when using context parameters. I have a TF module uploaded [here](https://registry.terraform.io/modules/sk593/redis/kubernetes/latest) based off this Github repo [here](https://github.com/sk593/terraform-kubernetes-redis/tree/main). Versions 1.0.0 - 3.0.0 have the recipe uploaded as a submodule and these fail deployment when using context parameters. Versions 4.0.0 - 6.0.0 were uploaded with the recipe at the root folder and these deploy successfully.

### Observed behavior (required)

Recipe deployment with the submodule uses a slightly different module source as the template path (note the `//` in the template path):
```
recipes: {
      'Applications.Core/extenders': {
        default: {
          templateKind: 'terraform'
          templatePath: 'sk593/redis/kubernetes//modules/kubernetes-redis'
          templateVersion: '>= 1.0.0, < 3.0.0'
        }
      }
    }
```

This fails with the following error:
```
Error: {
  "code": "DeploymentFailed",
  "message": "At least one resource deployment operation failed. Please see the details for the specific operation that failed.",
  "target": "/planes/radius/local/resourceGroups/default/providers/Microsoft.Resources/deployments/rad-deploy-3f98b05a-259c-4aa5-bbac-feaef33b0cf9",
  "details": [
    {
      "code": "OK",
      "message": "",
      "target": "/planes/radius/local/resourceGroups/default/providers/Applications.Core/applications/myapp"
    },
    {
      "code": "ResourceDeploymentFailure",
      "message": "Failed",
      "target": "/planes/radius/local/resourceGroups/default/providers/Applications.Core/extenders/corerp-resources-terraform-redis",
      "details": [
        {
          "code": "RecipeDeploymentFailed",
          "message": "terraform apply failure: exit status 1\n\nError: Missing required argument\n\n  on main.tf.json line 16, in module.default:\n  16:     }\n\nThe argument \"context\" is required, but no definition was found.\n"
        }
      ]
    },
    {
      "code": "OK",
      "message": "",
      "target": "/planes/radius/local/resourceGroups/default/providers/Applications.Core/environments/corerp-resources-terraform-redis-env"
    }
  ]
}

TraceId:  bba43582c0fde7f18a6b21d316c98548
```

### Desired behavior (required)

Ideally submodules should deploy successfully when using context parameters. 

### Proposed Fix (optional)

It seems like this issue occurs because we try to [load the module](https://github.com/radius-project/radius/blob/fcd096e43bf73e47a434708d43d28d56ebb1b1ba/pkg/recipes/terraform/module.go#L62C54-L62C54) that's at the root directory. But we need to access the submodule to find if there's a context variable. Terraform has a hard convention where they denote submodules using a `//` in the source. See here: https://developer.hashicorp.com/terraform/language/modules/sources#modules-in-package-sub-directories

Since this is their convention, we could parse the template paths for the double slash and then deploy the recipe that's in the nested submodule instead of only looking at the root. 

## Additional context

[AB#10855](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/10855)

**Comment by ytimocin** [comment]
I have also seen this issue in a few long running test. One of them: https://github.com/radius-project/radius/actions/runs/7592011049/job/20680831682.

**Comment by kachawla** [comment]
> I have also seen this issue in a few long running test. One of them: https://github.com/radius-project/radius/actions/runs/7592011049/job/20680831682.

We don't use submodules in our functional tests yet so it shouldn't be caused by this issue. Let me know if there is an overlap between the two scenarios that I'm missing here. Else let's track the investigation for the test failure in the another issue you logged: https://github.com/radius-project/radius/issues/7060

**Comment by ytimocin** [comment]
Yes, @kachawla that makes sense. I thought that these issues could be linked. I am good to track it in the other issue.
