### ISSUE TITLE
Functional Test Failure: Invalid Response for LouisBrunner/checks-action Step

### ISSUE THREAD

**Issue by kachawla** [radius-project/radius#7006]
## Bug information
Scheduled functional test failure: https://github.com/radius-project/radius/issues/7003

```Run LouisBrunner/checks-action@v[1](https://github.com/radius-project/radius/actions/runs/7461288980/job/20301269266#step:3:1).6.1
Error: invalid json response body at https://api.github.com/repos/radius-project/radius/check-runs reason: Unexpected end of JSON input
```

Link to the failed run: https://github.com/radius-project/radius/actions/runs/7461288980/job/20301269266

![Screenshot 2024-01-09 at 5 08 19 PM](https://github.com/radius-project/radius/assets/74574173/4952eb7e-eacc-44d0-b981-08d64a05fe0e)

![Screenshot 2024-01-09 at 5 08 10 PM](https://github.com/radius-project/radius/assets/74574173/dfb8fe1a-8e4d-4ead-a5f5-cfe8935ac85f)

### Steps to reproduce (required)

Unknown

### Observed behavior (required)

Added screenshots above.
Logs: 
[datastoresrp_container_logs.zip](https://github.com/radius-project/radius/files/13881695/datastoresrp_container_logs.zip)

### Desired behavior (required)

Functional tests should pass.

[AB#10856](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/10856)

**Comment by AaronCrawfis** [comment]
Triage: transient GitHub issue that was part of https://www.githubstatus.com/incidents/pxg3dz4yg7lp, please reopen if hit again
