### ISSUE TITLE
`rad install kubernetes --reinstall` behavior documentation - discussion kick off

### ISSUE THREAD

**Issue by ytimocin** [radius-project/radius#7007]
## Engineering Improvement
This issue will be more like an explanation of how `rad install kubernetes --reinstall` works as of now. From here on, we can start a discussion if we would like to change this behavior.

Summary:
1. `rad install kubernetes --reinstall` command recreates **applications-rp**, **bicep-de**, **controller**, and **ucp** pods even though there is no change in the Helm charts. At the same time, the secrets associated with these pods are not recreated. Please see the first attached screenshot.
2. `rad install kubernetes --reinstall` command doesn't recreate **contour** pods. Probably because there isn't any change to the Helm charts of them.
3. If you delete **sh.helm.release.v1.contour.*** and/or **sh.helm.release.v1.radius.*** secrets (which probably act as a checkpoint for the deployments) and then run `rad install kubernetes --reinstall`, the pods do not get recreated but the deleted secrets get recreated.
4. If you delete all the secrets in the **radius-system** namespace and then run `rad install kubernetes --reinstall`, the pods do not get recreated but all secrets get recreated.

### Area for Improvement (required)
We can discuss which one of these scenarios are expected or not expected. We can also discuss what should happen instead of what is stated above.

### Observed behavior (required)
In the first scenario above, because the secrets are not updated, I see failures in the webhook and reconciler functional tests. I believe that the secret also needs to be created like the pods so that we don't see any failures. This is the reason why running functional tests as one time doesn't cause errors. But as soon as we introduce `rad install kubernetes --reinstall` into the picture like we do in the long-haul test cluster, we start to see some errors.

Another behavior I observed is that, recreation of the secrets doesn't affect the Pod and in return I don't see x509 errors. But once the pods get recreated and at the same time secrets don't get recreated, like a link gets broken between the secret object and the pod object, I start to see x509 errors both in controller pods and ucp pods.

I will add my findings as I do more tests.

### Desired behavior (required)
1. `rad install kubernetes --reinstall` should recreate all pods and all secrets (and probably all necessary resources). Or if there is no change to the Helm charts, like contour does, it shouldn't recreate anything at all.

### Proposed Fix (optional)
Here is a comment written a long time ago: https://github.com/radius-project/radius/blob/main/pkg/cli/helm/radiusclient.go#L97. Not sure if that might be related. We should debug further and see why pods are being recreated but related secrets are not.

### rad Version (required)
RELEASE   VERSION   BICEP     COMMIT
0.29.0    v0.29.0   0.29.0    6abd7bfc3de0e748a2c34b721d95097afb6a2bba

### Operating system (required)
macOS, Apple Chip, Sonoma 14.2.1

## Additional context
**Note: you can check the **AGE** in the attached screenshots.**

![image](https://github.com/radius-project/radius/assets/5220939/e35747df-2160-4146-bc53-0b000c909117)
**_1) `rad install kubernetes --reinstall` recreates the pods but not the secrets._**

![image](https://github.com/radius-project/radius/assets/5220939/9ebf6f5f-3ea5-4873-91a4-a366ead5fcd0)
**_2) after deleting all secrets, calling`rad install kubernetes --reinstall` recreates the secrets but not the pods._**

[AB#10857](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/10857)

**Comment by youngbupark** [comment]
The below are expected. Kubernetes doesn't recreate Pod if Deployment and PodSpec are same as before. `--reinstall` will recreate Pod when user upgrades radius to the next version because there is change in image tag. 

> rad install kubernetes --reinstall command recreates applications-rp, bicep-de, controller, and ucp pods even though there is no change in the Helm charts. At the same time, the secrets associated with these pods are not recreated. Please see the first attached screenshot.
> rad install kubernetes --reinstall command doesn't recreate contour pods. Probably because there isn't any change to the Helm charts of them.

The right upgrade scenario should not recreate the secret. instead, it should reuse the secret in pod so that existing running pod should not be impacted. Otherwise, it might cause the downtime of the service.

> If you delete sh.helm.release.v1.contour.* and/or sh.helm.release.v1.radius.* secrets (which probably act as a checkpoint for the deployments) and then run rad install kubernetes --reinstall, the pods do not get recreated but the deleted secrets get recreated.
> If you delete all the secrets in the radius-system namespace and then run rad install kubernetes --reinstall, the pods do not get recreated but all secrets get recreated.

**Comment by AaronCrawfis** [comment]
Triage: this is expected behavior. @youngbupark and @ytimocin are working offline to develop next steps.
