### ISSUE TITLE
Missing Annotations and Labels on Kubernetes Resources Deployed via bicep using `rad deploy`

### ISSUE THREAD

**Issue by kachawla** [radius-project/radius#7024]
## Bug information
When deploying a Kubernetes resource using Bicep's Kubernetes extensibility provider through `rad deploy`, labels and annotations are not being applied. For example, when deploying a resource like the one defined [here](https://github.com/radius-project/samples/blob/c4fef4d96fbd99cd8bbd80ef928e51049601cad8/samples/dapr/dapr.bicep#L86C1-L147).

However, when attempting deployment through the [Azure CLI](https://learn.microsoft.com/en-us/azure/azure-resource-manager/bicep/bicep-extensibility-kubernetes-provider), all the expected metadata is present on the deployed resource. It is likely that we need to rebase Radius' Bicep fork with the latest Bicep to pull in updates for the Kubernetes provider.

### Steps to reproduce

Define a resource in a bicep file using the Kubernetes extensibility provider, such as the one specified here: https://github.com/radius-project/samples/blob/c4fef4d96fbd99cd8bbd80ef928e51049601cad8/samples/dapr/dapr.bicep#L86C1-L147, or in the snippet below:

```
resource service 'core/Service@v1' = {
  metadata: {
    name: 'redis'
    labels: {
      app: 'redis'
    }
  }
  spec: {
    clusterIP: 'None'
    ports: [
      {
        port: 6379
      }
    ]
    selector: {
      app: 'redis'
    }
  }
}
```
Deploy this bicep file using `rad deploy`. Run `kubectl describe` to validate if labels and annotations defined in the bicep file are present on the created Kubernetes resource.

### Observed behavior

Defined annotations and labels are not applied to the created Kubernetes resource.

### Desired behavior

All the defined metadata should be present.

### rad Version

% rad version
RELEASE   VERSION   BICEP     COMMIT
0.29.0    v0.29.0   0.29.0    6abd7bfc3de0e748a2c34b721d95097afb6a2bba

### Operating system

macOS

[AB#10878](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/10878)

**Comment by rynowak** [comment]
I figured out why I was confused about this. My scenario is using the pod template to set labels on pods. That's different than setting labels on the top level object. 

I'm using the following recipe in demos:

```bicep
import kubernetes as kubernetes {
  kubeConfig: ''
  namespace: context.runtime.kubernetes.namespace
}

param context object

resource redis 'apps/Deployment@v1' = {
  metadata: {
    name: 'redis-${uniqueString(context.resource.id)}'
  }
  spec: {
    selector: {
      matchLabels: {
        app: 'redis'
        resource: context.resource.name
      }
    }
    template: {
      metadata: {
        labels: {
          app: 'redis'
          resource: context.resource.name
          'radius.dev/application': context.application.name
        }
      }
      spec: {
        containers: [
          {
            name: 'redis'
            image: 'redis'
            ports: [
              {
                containerPort: 6379
              }
            ]
          }
          {
            name: 'redis-cli'
            image: 'redis'
            args: [
              'redis-cli'
              '-h'
              'localhost'
              'MONITOR'
            ]
          }
        ]
      }
    }
  }
}

resource svc 'core/Service@v1' = {
  metadata: {
    name: 'redis-${uniqueString(context.resource.id)}'
  }
  spec: {
    type: 'ClusterIP'
    selector: {
      app: 'redis'
      resource: context.resource.name
    }
    ports: [
      {
        port: 6379
      }
    ]
  }
}

output result object = {
  // This workaround is needed because the deployment engine omits Kubernetes resources from its output.
  //
  // Once this gap is addressed, users won't need to do this.
  resources: [
    '/planes/kubernetes/local/namespaces/${svc.metadata.namespace}/providers/core/Service/${svc.metadata.name}'
    '/planes/kubernetes/local/namespaces/${redis.metadata.namespace}/providers/apps/Deployment/${redis.metadata.name}'
  ]
  values: {
    host: '${svc.metadata.name}.${svc.metadata.namespace}.svc.cluster.local'
    port: 6379
  }
}

```
