### ISSUE TITLE
Add Additonal K8s supported cluster

### ISSUE THREAD

**Issue by kevinevans1** [radius-project/radius#7046]
### Overview of feature request

Hello

Would it be possible to add MicroK8s to support cluster list ?

https://microk8s.io/

### Acceptance criteria

Compatibility to run with local BareMetal k8s cluster. 

### Additional context

Checkout the microk8s website. https://microk8s.io/

### Would you like to support us?

- [X] Yes, I would like to support you

[AB#10937](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/10937)

**Comment by willtsai** [comment]
@kevinevans1 - have you confirmed that Radius runs successfully on MicroK8s? If it uses standard Kubernetes, Radius should theoretically run on it without issues, but it's better to confirm first.

If so, then we can just move this issue into the `docs` repo for adding MicroK8s to the list of supported clusters.

**Comment by gpltaylor** [comment]
I have created a new VM in Azure and installed Micok8s and tested the basic "getting started" demo.

The commands used to setup where very easy.
```
sudo snap install microk8s --classic
microk8s status --wait-ready
sudo microk8s status --wait-ready
# need to add my account and login again
sudo usermod -a -G microk8s giz@xxx.co.uk
sudo chown -R giz@xxx.co.uk ~/.kube

microk8s
microk8s status
sudo microk8s status
# I need a .kube setup... lets add one manually
mkdir .kube
sudo chown -R gizadmin@xxx.co.uk ~/.kube
microk8s config view > ~/.kube/config

microk8s status
microk8s enable dashboard
microk8s get namespaces
microk8s kubectl get namespaces

wget -q "https://raw.githubusercontent.com/radius-project/radius/main/deploy/install.sh" -O - | /bin/bash

mkdir first-app
cd first-app

rad install kubernetes

rad init
vim app.bicep
rad run app.bicep

rad app connections
microk8s kubectl get namespaces
```

This worked perfectly.

The test is of course simple, but on face value I think we can say that Microk8s is supported.

VM Details: Ubuntu 20.04.6 LTS (GNU/Linux 5.15.0-1053-azure x86_64)

## References
[Getting Started](https://docs.radapp.io/getting-started/)
[Installing Microk8s](https://microk8s.io/#install-microk8s)

## Screenshots
<img width="656" alt="microk8s-vs-radius-e" src="https://github.com/radius-project/radius/assets/3308167/604c27ed-3902-4dcc-a82d-5c31dbb81100">
<img width="1252" alt="microk8s-vs-radius-d" src="https://github.com/radius-project/radius/assets/3308167/032e3657-7f72-44c4-8f63-22d2a0fe0e4a">
<img width="748" alt="microk8s-vs-radius-c" src="https://github.com/radius-project/radius/assets/3308167/7592cc1c-8f4b-4b33-953b-0219c101f78b">
<img width="724" alt="microk8s-vs-radius-b" src="https://github.com/radius-project/radius/assets/3308167/171390c7-3978-4faa-a18a-705c3ea85edf">
<img width="991" alt="microk8s-vs-radius-a" src="https://github.com/radius-project/radius/assets/3308167/7d908ed0-9aed-476d-b006-d3999f4a290d">

**Comment by kevinevans1** [comment]
Thanks , I also did the same. Validated and tested.
