### ISSUE TITLE
Support SecretStore in container resource (Native Radius Way) for `k8s Secrets`.

### ISSUE THREAD

**Issue by tdeheurles** [radius-project/radius#7051]
### Overview of feature request

Right now, Radius do not support secretstore for referring existing k8s secret as a volume in container.  So we are have to use podSpec.

Maybe container resource could support this or a documentation could be present in secretstore as a starting point ?

Here is an example:
```bicep
resource container 'Applications.Core/containers@2023-10-01-preview' = {
  name: 'ctnr-podpatch'
  location: location
  properties: {
    application: app.id
    container: {
      image: magpieimage
      ports: {
        web: {
          containerPort: port
        }
      }
    }
    connections: {}
    runtimes: {
      kubernetes: {
        pod: { // This is free-form object, you can use any kubernetes podSpec properties.
          containers: [
            {
              name: 'ctnr-podpatch' // ensure that it matches the container name above
              volumeMounts: [
                {
                  name: 'se-charlie-server'
                  mountPath: '/credentials'
                  readOnly: true
                }
              ]
            }
          ]
          volumes: [
            {
              name: 'se-charlie-server'
              secret: {
                secretName: 'se-charlie-server'
              }
            }
          ]
        }
      }
    }
  }
}
```

FYI @youngbupark 

### Acceptance criteria

Options:

### Additional context

See the [topic on discord forum](https://discord.com/channels/1113519723347456110/1197133077487570975)

### Would you like to support us?

- [ ] Yes, I would like to support you

[AB#10953](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/10953)

**Comment by youngbupark** [comment]
@willtsai  This is related to https://github.com/radius-project/radius/issues/5520. We need to support more use-cases of secretstore for containers. e.g. volume mount, secret reference in fields in container resource or any radius resource. 

cc/ @rynowak

**Comment by rynowak** [comment]
Yup. This is badly needed.

**Comment by willtsai** [comment]
this is completed as a part of https://github.com/radius-project/radius/pull/7744/
