### ISSUE TITLE
Applications.Core/secretStores list and delete cli commands giving wrong data.

### ISSUE THREAD

**Issue by vishwahiremat** [radius-project/radius#7070]
### Steps to reproduce

Deploy a bicep with secret store resource
```
 ~/radius> rad deploy corerp-resources-gateway-tlstermination.bicep

Building test/functional/shared/resources/testdata/corerp-resources-gateway-tlstermination.bicep...
Deploying template 'test/functional/shared/resources/testdata/corerp-resources-gateway-tlstermination.bicep' into environment 'default' from workspace 'dev'...

Deployment In Progress...

Completed            corerp-resources-gateway-tlstermination Applications.Core/applications
..                   tls-gtwy-front-ctnr Applications.Core/containers
Completed            tls-gtwy-cert1312 Applications.Core/secretStores
..                   tls-gtwy-gtwy   Applications.Core/gateways

Deployment Complete

Resources:
    corerp-resources-gateway-tlstermination Applications.Core/applications
    tls-gtwy-front-ctnr Applications.Core/containers
    tls-gtwy-gtwy   Applications.Core/gateways
    tls-gtwy-cert1312 Applications.Core/secretStores

Public Endpoints:
    tls-gtwy-gtwy   Applications.Core/gateways https://tls-gtwy-gtwy.corerp-resources-gateway-tlstermination.172.19.0.3.nip.io
 ~/radius > rad resource list secretstores
```
List the secrets deployed in the above bicep file
```
 ~/Documents/RadiusProject/radius > rad resource list secretstores                                                                                        
RESOURCE  TYPE      GROUP     STATE
```
Returns empty list and same with delete command.

### Observed behavior

With the split namespace changes we updated `Applications.Link/daprSecretStores` -> `Applications.Dapr/secretStores` and   in `rad resource` commands we only take the resource type(i.e `secretStores` and not `Applications.Dapr/secretStores`) as input and  it matches with the resource type of `Application.Core/secretStores`
![image](https://github.com/radius-project/radius/assets/100623239/63ca5fb4-b00d-489a-bccf-7b58df2d2bdf)

Because of the same name for resource-type it either works for daprSecrets/coreSecrets. Since Applications.Dapr/secretStores is above Applications.Dapr/secretStores here in this list, list and delete commands are looking for daprSecrets.
https://github.com/radius-project/radius/blob/479bd51f9a92bf5c1ab98b3e83dffdd4cb1a4568/pkg/cli/clients/management.go#L52-L67

### Desired behavior

resource list and delete commands for Application.Core/secretStores should  provide right data i.e information on the coreSecrets rather than daprSecrets.

### Workaround

https://github.com/radius-project/radius/blob/479bd51f9a92bf5c1ab98b3e83dffdd4cb1a4568/pkg/cli/clients/management.go#L52-L67

moved `sstr_ctrl.ResourceTypeName` to top of the list to get unblocked.

Long term fix could be:

Option1 : Provide complete resource type in rad resource commands for all resources.
e.g:

`rad resource list Application.Core/secretStores`  (or)  `rad resource list Application.Dapr/secretStores`

Option2 : change the type of `Application.Dapr/secretStores` from secretStores to daprSecretStores in cli argument.

`rad resource list daprSecretStores`

### rad Version

```
$ rad version
RELEASE   VERSION   BICEP     COMMIT
0.29.0    v0.29.0   0.29.0    6abd7bfc3de0e748a2c34b721d95097afb6a2bba
```

### Operating system

macOS, Sanoma, M1 chip

### Would you like to support us?

- [ ] Yes, I would like to support you

[AB#10984](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/10984)

**Comment by shalabhms** [comment]
Related issue : https://github.com/radius-project/radius/issues/5889

**Comment by AaronCrawfis** [comment]
We should look at how kubectl handles this. In general, resources will have a fully-qualified resource type, and a short name. The rad CLI should always accept the fully qualified name (`Applications.Datastores/redisCaches`), and when there are no conflicts accept the shortname (`redisCaches`). If there are conflicts (`secretStores`), then we should return an error to the user saying the resourceType, 'secretStores' is ambiguous, with all matching fully-qualified types printed, and for the user to specify a fully qualified name.

We shouldn't rename our types to prevent conflicts across namespaces. We should always assume there will be conflicts on shortnames across namespaces.

Here's what should happen instead:

```bash
$ rad resource list secretsStores
Error: multiple resource types match 'secretStores'. Please specify the full resource type and try again:

Applications.Dapr/secretStores
Applications.Core/secretStores
```
