### ISSUE TITLE
Release notes are not automatically generated for the release

### ISSUE THREAD

**Issue by vinayada1** [radius-project/radius#7106]
### Steps to reproduce

release.yaml workflow was skipped on the release PR: https://github.com/radius-project/radius/pull/7103/files due to a recent change in the workflow file.

### Desired behavior

Release notes should be automatically generated

### rad Version

0.29

### Would you like to support us?

- [ ] Yes, I would like to support you

[AB#11091](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/11091)

**Comment by nicolejms** [comment]
more than likely a duplicate. will need to find it
