### ISSUE TITLE
Add instructions for granting on-call engineers repository permissions

### ISSUE THREAD

**Issue by sk593** [radius-project/radius#7172]
We recently updated our repositories to only allow read and write access for maintainers and approvers. We've run into a few limitations where the on-call engineer doesn't have sufficient permissions to merge PRs, close issues, etc depending on which repository they're working in. 

We should investigate if there's a way to temporarily grant repository access since these permissions will be needed to complete on-call/release work smoothly. The instructions for gaining and granting access should be documented in the community repository as well. 

[AB#11168](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/11168)

**Comment by willdavsmith** [comment]
We should also make sure the on-call engineer has access to publish the VSCode Bicep extension

**Comment by willdavsmith** [comment]
Idea: GitHub team which has write access to each of the repos

**Comment by nicolejms** [comment]
This has been completed. There is an on-call team that has write access these repos: 
[Yesterday 10:19 AM] Will Smith
radius
bicep
deployment-engine
samples
docs
dashboard
bicep-types-aws
recipes
 
community docs have been updated.
