### ISSUE TITLE
remove rad app connections alias

### ISSUE THREAD

**Issue by nithyatsu** [radius-project/radius#7262]
We have rad app connections as an alias for rad app graph. 
Our documents are updated to rad app graph, and we are retaining connections for backward compatibility. 
We should remove it at an agreed upon schedule. 

[AB#11346](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/11346)

**Comment by willtsai** [comment]
Audit the docs to make sure all references to the command `rad app connections` have been updated to `rad app graph`
