### ISSUE TITLE
remove necessity for functional test approval if there are no new commits 

### ISSUE THREAD

**Issue by nithyatsu** [radius-project/radius#7263]
We currently need an approval for running functional test when we rebase on latest main, but there is no new code. 
it would be good to remove the approval requirement for this scenario.

[AB#11362](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/11362)

**Comment by sylvainsf** [comment]
If there's a change in main that causes the new code to break the functional tests would catch that.

**Comment by nithyatsu** [comment]
@sylvainsf , I did not mean functional tests as not required, but was looking at the possiblity of removing "approval" for functional tests run, since there is no new commit and hance no new threat.
