### ISSUE TITLE
`rad recipe show` doesn't work with private Terraform modules

### ISSUE THREAD

**Issue by AaronCrawfis** [radius-project/radius#7267]
If you try to run `rad recipe show` with a private Terraform module it throws an error showing a permissions error when trying to access the module.

This is due to git credentials not being configured correctly when terraform plan is run when trying to access the variables of the module.

## Error Message

```
Error: {
  "code": "Internal",
  "message": "code RecipeGetMetadataFailed: err code RecipeDownloadFailed: err failed to run terraform get to download the module from source \"git::https://github.com/vishwa1312/test-redis-terraform\": exit status 1\n\nError: Failed to download module\n\n  on main.tf.json line 4, in module:\n   4:     \"default\": {\n\nCould not download module \"default\" (main.tf.json:4) source code from\n\"git::https://github.com/vishwa1312/test-redis-terraform\": error downloading\n'https://github.com/vishwa1312/test-redis-terraform': /usr/bin/git exited\nwith 128: Cloning into '.terraform/modules/default'...\nfatal: could not read Username for 'https://github.com': No such device or\naddress\n\n\n"
}
```

## Definition of Done

1. A user can run `rad recipe show` for a Terraform Recipe with a private git module and it will display correctly, with the variables shown correctly.
2. The how-to guide for TF private modules needs to be updated with a final step to use this command to prove that the Recipe was added correctly.

[AB#11365](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/11365)

**Comment by vishwahiremat** [comment]
Error:
```
Error: {
  "code": "Internal",
  "message": "code RecipeGetMetadataFailed: err code RecipeDownloadFailed: err failed to run terraform get to download the module from source \"git::https://github.com/vishwa1312/test-redis-terraform\": exit status 1\n\nError: Failed to download module\n\n  on main.tf.json line 4, in module:\n   4:     \"default\": {\n\nCould not download module \"default\" (main.tf.json:4) source code from\n\"git::https://github.com/vishwa1312/test-redis-terraform\": error downloading\n'https://github.com/vishwa1312/test-redis-terraform': /usr/bin/git exited\nwith 128: Cloning into '.terraform/modules/default'...\nfatal: could not read Username for 'https://github.com': No such device or\naddress\n\n\n"
}
```

**Comment by ytimocin** [comment]
Does this require a patch? @AaronCrawfis

**Comment by AaronCrawfis** [comment]
> Does this require a patch? @AaronCrawfis

I don't believe so, it doesn't break flows when not using private TF modules so there's no regression. We'll get it in an upcoming release.
