### ISSUE TITLE
Log Errors for Failed Requests

### ISSUE THREAD

**Issue by kachawla** [radius-project/radius#7297]
### Problem

We currently lack error logging upon failure for many operations which hinders our ability to debug failures. This gap exists because errors that aren't propagated back up (async operations) [aren't logged automatically](https://github.com/radius-project/radius/blob/main/docs/contributing/contributing-code/contributing-code-control-plane/logging.md?plain=1#L45). The current state of the code is inconsistent, with some operations logging errors while others do not.

Here is an example of where error was not logged: https://github.com/radius-project/radius/issues/7264

### Proposed Solution
To address this, the proposed change is to move error logging to the setFailed method. By doing so, we ensure that error logging is not reliant on every individual operation to log errors.

[AB#11425](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/11425)

**Comment by nithyatsu** [comment]
@kachawla , is the issue easy to reproduce? if so, could you please share the steps with me, I will look into this.

**Comment by kachawla** [comment]
> @kachawla , is the issue easy to reproduce? if so, could you please share the steps with me, I will look into this. I went through the PR's approach of propagating the error. I am trying to understand why the logs get dropped.

@nithyatsu thanks for looking into this. Here is an example of where it happened: https://github.com/radius-project/radius/issues/7264. So if we run into an error on the delete resource path for portable resources, we will run into this. This gap exists on core rp resource creation/deletion as well should also be reproducible by injecting error on any of those paths as well. It is basically similar issue as what you fixed for create/update requests for portable resources here: https://github.com/radius-project/radius/pull/6276

**Comment by youngbupark** [comment]
This is the error log from functional tests. This is coming from k8s API server and sdk. Unless we can get all logs from k8s related pods, it is hard to figure it out why. And it is also difficult to repro. I am sure that Radius was working as expected, but K8s API server was not working as expected. If we could see the similar issue in long-running test, we would be able to get more details from log analytics because long-running test logs all k8s related pods.

```
2024/03/05 04:16:27 Start streaming Kubernetes logs - Pod dapr-frontend-5448d95787-8dhhg is in state: Failed
    cli.go:418: [rad] Error: {
    cli.go:418: [rad]   "code": "Internal",
    cli.go:418: [rad]   "message": "could not find API version for type \"core/Secret\": unable to retrieve the complete list of server APIs: metrics.k8s.io/v1beta1: the server is currently unable to handle the request"
```

**Comment by kachawla** [comment]
> This is the error log from functional tests. This is coming from k8s API server and sdk. Unless we can get all logs from k8s related pods, it is hard to figure it out why. And it is also difficult to repro. I am sure that Radius was working as expected, but K8s API server was not working as expected. If we could see the similar issue in long-running test, we would be able to get more details from log analytics because long-running test logs all k8s related pods.
> 
> ```
> 2024/03/05 04:16:27 Start streaming Kubernetes logs - Pod dapr-frontend-5448d95787-8dhhg is in state: Failed
>     cli.go:418: [rad] Error: {
>     cli.go:418: [rad]   "code": "Internal",
>     cli.go:418: [rad]   "message": "could not find API version for type \"core/Secret\": unable to retrieve the complete list of server APIs: metrics.k8s.io/v1beta1: the server is currently unable to handle the request"
> ```

I had seen this log already :), had added it here since Logging done by functional tests were available https://github.com/radius-project/radius/issues/7264#issuecomment-1979698138. But if you search through the RP logs (attached in this comment https://github.com/radius-project/radius/issues/7264#issuecomment-1986694133), this error isn't logged, which is a gap that I have seen in other places as well and am trying to figure out. I'm sure we can reproduce it by injecting any client side error.

**Comment by kachawla** [comment]
Fixed in https://github.com/radius-project/radius/pull/7370 and created https://github.com/radius-project/radius/issues/7369 with suggestions on further improvements in the async worker.
