### ISSUE TITLE
Add workload identity support to the Azure provider

### ISSUE THREAD

**Issue by AaronCrawfis** [radius-project/radius#7308]
## Current State

Today when you register the Azure provider `rad provider register azure`, it requires a client_id and a client_secret, referring to an Entra ID application registration. This is how UCP connects to Azure in order to deploy Azure resources.

## Desired State

We should also support managed identities, leveraging the workload identity project where the cluster is federated to the app registration and there are no secrets to keep or rotate.

Ideally a user would:

1. Setup workload identity on their cluster
2. Create an app registration in Entra ID
3. Register their Azure provider with the app registration (client_id), but use workload identity instead of a client-secret.

### Feature 1 : rad init interactive experience supports Workload Identity

rad init interactive experience supports additional prompts for workload identity. Once the user enables workload identity for Azure cloud provider, the control plane pods are patched with Azure workload identity labels and annotations. 

### Feature 2 : Non-interactive CLI supports Workload Identity 

rad install and rad credential support azure-workload-identity-app-id option for user to register the federated credentials to Radius.

### Feature 3 : DE, UCP, Applications RP supports Workload Identity auth

Use Azure client library and add workload-identity auth option.

[AB#11482](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/11482)

**Comment by nicolejms** [comment]
We will a short functional spec to understand cli and any other user facing changes

**Comment by willtsai** [comment]
The three key features coming out of this work will be:

### Feature 1 : rad init interactive experience supports Workload Identity

rad init interactive experience supports additional prompts for workload identity. Once the user enables workload identity for Azure cloud provider, the control plane pods are patched with Azure workload identity labels and annotations. 

### Feature 2 : Non-interactive CLI supports Workload Identity 

rad install and rad credential support azure-workload-identity-app-id option for user to register the federated credentials to Radius.


### Feature 3 : DE, UCP, Applications RP supports Workload Identity auth

Use Azure client library and add workload-identity auth option.

**Comment by willdavsmith** [comment]
closed by https://github.com/radius-project/radius/pull/7640
