### ISSUE TITLE
Add `README.MD` to the public view of the Radius org on GitHub

### ISSUE THREAD

**Issue by jasonviviano** [radius-project/radius#7310]
### Overview of feature request

In the GitHub UI we have 2 distinct views for our GitHub org, I was thinking that the small `README.MD`
that creates that big section in the member view might be useful to showcase in the public view as well since it has lots of info and calls to action. If someone has permission to change that stuff might be a nice small change to make.

### Acceptance criteria

Public view displays the `readme.md`

### Additional context

Member View:
![Screenshot 2024-03-12 at 5 42 34 PM](https://github.com/radius-project/radius/assets/83607984/1980f417-a9ff-495e-a277-d18c08502ee8)

Public View:
![Screenshot 2024-03-12 at 5 42 50 PM](https://github.com/radius-project/radius/assets/83607984/3ca0200e-1f19-414c-8c96-3341af45c8f0)

### Would you like to support us?

- [ ] Yes, I would like to support you

[AB#11485](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/11485)

**Comment by AaronCrawfis** [comment]
Looks like we haven't added a public version of the README. See this for instructions on how to fix: https://docs.github.com/en/organizations/collaborating-with-groups-in-organizations/customizing-your-organizations-profile#adding-a-public-organization-profile-readme

**Comment by jasonviviano** [comment]
Also this is an issue that can only be resolved by someone with organization level permissions as it requires creating a new repo inside of the org
