### ISSUE TITLE
Remove MD from .gitignore in Bicep repo

### ISSUE THREAD

**Issue by ytimocin** [radius-project/radius#7360]
### Overview of feature request

We need to remove the MD files from the .gitignore in the Bicep repo.

### Additional context

Link to the discussion on the 0.31 PIR: https://microsoft.sharepoint.com/:w:/t/radiuscoreteam/EYDkNC_uZalJi0-CJqEbOpkBj31i-4onDwqAewPTDJHkdw?e=kxQsU5&nav=eyJjIjoxMDE4NzQ0Mzk3fQ%3D%3D

### Would you like to support us?

- [ ] Yes, I would like to support you

[AB#11572](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/11572)

**Comment by ytimocin** [comment]
cc/ @AaronCrawfis @sk593 @kachawla

**Comment by kachawla** [comment]
Closing this since it is already covered in https://github.com/radius-project/radius/issues/7356. @ytimocin does that sound right?
