### ISSUE TITLE
`rad group show` doesn't show the current group

### ISSUE THREAD

**Issue by ytimocin** [radius-project/radius#7391]
### Steps to reproduce

Not sure if this is expected but unlike `rad workspace show` or `rad env show`, `rad group show` doesn't show the current/active group.

### Observed behavior

![image](https://github.com/radius-project/radius/assets/5220939/ba3053f8-7f06-47ba-8ed8-396dbfcb6f45)

### Desired behavior

`rad group show` should show the current/active group.

### rad Version

RELEASE   VERSION   BICEP     COMMIT
0.31.0    v0.31.0   0.31.0    3fa840730295681733357e7c94e6813d04cfae6d

### Operating system

macOS, Apple M1 Pro, Sonoma 14.4

### Would you like to support us?

- [ ] Yes, I would like to support you

[AB#11624](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/11624)

**Comment by AaronCrawfis** [comment]
@ytimocin do you have a resource group set? What happens if you run `rad group switch` and then `rad group show`? This error message is usually thrown when you haven't set a default group and you also haven't specified one.

**Comment by AaronCrawfis** [comment]
Update: just checked and am able to recreate:

```powershell
$ rad group switch default
$ rad group show
Error: resource group name is not provided or is empty

TraceId:  a026ddda0e30df12501ea5d98f0413f5

$ cat ~/.rad/config.yaml
workspaces:
    default: default
    items:
        default:
            connection:
                context: k3d-k3s-default
                kind: kubernetes
            environment: /planes/radius/local/resourceGroups/default/providers/Applications.Core/environments/default
            scope: /planes/radius/local/resourceGroups/default
$ rad group show
Error: resource group name is not provided or is empty

TraceId:  94445ed5c115df850378917bfafc4fb4

  ~ 
```
