### ISSUE TITLE
`rad group switch` doesn't print success message

### ISSUE THREAD

**Issue by ytimocin** [radius-project/radius#7395]
### Steps to reproduce

1. `rad group create test`
2. `rad group switch test`
3. See there is no message saying that the group was successfully switched

### Observed behavior

![image](https://github.com/radius-project/radius/assets/5220939/0b98e43f-1694-4d7a-8f96-b7942cdea1c4)

### Desired behavior

The CLI should tell me that the switch successfully happened.

### rad Version

0.31

### Would you like to support us?

- [ ] Yes, I would like to support you

[AB#11631](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/11631)

**Comment by nicolejms** [comment]
fit and finish. As good first issue, please add information on where the code is, etc. for new contributor.

**Comment by ytimocin** [comment]
Here is where the logic of switching groups resides: https://github.com/radius-project/radius/blob/main/pkg/cli/cmd/group/groupswitch/switch.go. We need to do updates in this file but also shouldn't forget to create/update necessary unit and functional tests.
