### ISSUE TITLE
Switch Azure DevOps Sync tool to use a service principal instead of a PAT

### ISSUE THREAD

**Issue by AaronCrawfis** [radius-project/radius#7402]
Azure DevOps recently added service principal auth: https://learn.microsoft.com/en-us/azure/devops/integrate/get-started/authentication/service-principal-managed-identity?view=azure-devops

We should switch our sync workflows to use managed identities instead of a PAT.

Note that this will require the sync tool to make changes: https://github.com/danhellem/github-actions-issue-to-work-item/issues/142

Once this is merged and a new release is available, we can update our workflows. Here's a pattern of what we can do (note the token passing wasn't working as expected but this is a strong start): https://github.com/radius-project/docs/blob/v0.31/.github/workflows/issues.yml#L35-L65

[AB#11648](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/11648)
```[tasklist]
### Repos to update
- [x] `dashboard`
- [x] `docs`
- [ ] `radius`
- [x] `samples`
- [ ] `recipes`
- [ ] `bicep-types-aws`
```

**Comment by willtsai** [comment]
I'm running into some issues with authenticating into Azure, will work with @AaronCrawfis on this.
https://github.com/radius-project/dashboard/actions/runs/8710057735/job/23893436352

**Comment by willtsai** [comment]
successfully implemented on the `dashboard` repo, moving on to the others now.

https://github.com/radius-project/dashboard/actions/runs/8804755985

**Comment by willtsai** [comment]
PRs for remaining repos:
- https://github.com/radius-project/bicep-types-aws/pull/41
