### ISSUE TITLE
Failing OpenSSF Workflow

### ISSUE THREAD

**Issue by kachawla** [radius-project/radius#7404]
OpenSSF Workflow has started failing since last week https://github.com/radius-project/radius/actions/workflows/scorecard.yaml. Needs further investigation on if this is caused by a change we made or something else.

[AB#11657](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/11657)

**Comment by nicolejms** [comment]
need to update node.js 2.0

**Comment by youngbupark** [comment]
OpenSSF is green now.

<img width="1313" alt="image" src="https://github.com/radius-project/radius/assets/11863108/24d97d25-81ed-4206-8183-463709cfccf2">

cc/ @nicolejms @rynowak
