### ISSUE TITLE
Functional Test Gaps for CLI

### ISSUE THREAD

**Issue by kachawla** [radius-project/radius#7453]
Our CLI functional test coverage is currently inconsistent, with several commands lacking any tests, including env show, list, app switch, among others. Although we introduced helper functions (removed in [this PR](https://github.com/radius-project/radius/pull/7445/files)) within the test framework for these commands, they were never utilized to implement actual tests. This issue aims to perform a review of our CLI functional test coverage and identify commands that are missing tests.

Next steps:

- [ ] Review the overall test coverage of our CLI commands.
- [ ] Identify commands that lack sufficient test coverage.
- [ ] Implement tests for commands lacking coverage.

[AB#11714](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/11714)

**Comment by sylvainsf** [comment]
Due to integration test coverage of the CLI most all of the code paths are covered, particularly in complex areas. Going forward we will take a leave it better than we found it approach and add functional tests if we modify functionality or move the CLI to its own repo.
