### ISSUE TITLE
rad app graph allows a -e flag which takes no effect

### ISSUE THREAD

**Issue by nithyatsu** [radius-project/radius#7507]
## Steps to reproduce:

Use [`rad app graph`](https://docs.radapp.io/reference/cli/rad_application_graph/) command to query for an application and pass in a nonexistent environment name using the `-e` flag:
```
nithya@Nithyas-MacBook-Pro bug7052 % rad app graph corerp-resources-gateway -e doesntexist 
Displaying application: corerp-resources-gateway

Name: http-gtwy-back-ctnr (Applications.Core/containers)
Connections:
  http-gtwy-back-rte (Applications.Core/httpRoutes) -> http-gtwy-back-ctnr
Resources:
:
```

## Observed behavior

The `-e` flag has no effect on the command.

## Desired behavior

The `-e` flag gets taken under consideration for the command:
- query for the application in the specified environment
- if the application does not exist in the environment, show error to user ("The application was not found in the specified environment", or something similar)
- if the environment does not exist, show error to user ("The specified environment was not found", or something similar)

[AB#11781](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/11781)

**Comment by sylvainsf** [comment]
Agreed this should be covered properly.

**Comment by kachawla** [comment]
Upon looking into this further and evaluating the supported options for of rest of the `rad app` commands, we have decided that we will remove the `-environment` flag from `rad app graph` command. This flag and filtering based on environment name is currently not supported in other `rad app` commands. Environment based filtering will be implemented on all `rad app` commands in the future, if needed as we get more feedback.
