### ISSUE TITLE
Unable to display APP GRAPH in dashboard

### ISSUE THREAD

**Issue by kboro** [radius-project/radius#7525]
### Steps to reproduce

OS Windows 11
Kubernetes  - minikube version: v1.32.0

Install and run demo application with following instruction: https://docs.radapp.io/installation/

### Observed behavior

While trying to get APP GRAPH from dashboard : http://localhost:7007/resources/default/Applications.Core/applications/rad-demo/application

I receive:

```
ApplicationTab.tsx:57 

POST http://localhost:7007/api/kubernetes/proxy/apis/api.ucp.dev/v1alpha3//planes/radius/local/resourcegroups/default/providers/Applications.Core/applications/rad-demo/getGraph?api-version=2023-10-01-preview 403 (Forbidden)

```
![image](https://github.com/radius-project/radius/assets/28050787/3de7a71a-c761-46d9-b080-3c3b5040bb00)

### Desired behavior

APP GRAPH is displaying resources. 

### rad Version

RELEASE   VERSION   BICEP     COMMIT
0.32.0    v0.32.0   0.32.0    1b8bd4ad7f7a3f9d88b1275b284f7357915a914e

### Operating system

Windows 11
Kubernetes  - minikube version: v1.32.0

### Would you like to support us?

- [X] Yes, I would like to support you

[AB#11926](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/11926)

**Comment by sylvainsf** [comment]
We have a fix for this coming in the next release. Thanks for reporting!

**Comment by willdavsmith** [comment]
Fixed by: https://github.com/radius-project/radius/pull/7478/files

It will be available in this week's release :) here's further explanation and a workaround @kboro : https://github.com/radius-project/dashboard/issues/68
