### ISSUE TITLE
migrate golang/mock to uber-go/mock

### ISSUE THREAD

**Issue by youngbupark** [radius-project/radius#7543]
### Overview of feature request

Google no longer maintains golang/mock project. Uber takes it over and maintains this project. https://github.com/uber-go/mock 

For the future upgrade, we should migrate golang/mock to uber-go/mock.

### Would you like to support us?

- [X] Yes, I would like to support you

[AB#12059](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/12059)

**Comment by sylvainsf** [comment]
We aren't sure if this would be a drop-in replacement but we would welcome partial progress from the community.

**Comment by youngbupark** [comment]
> We aren't sure if this would be a drop-in replacement but we would welcome partial progress from the community.

It is drop-in replacement. golang team no longer maintains go-mock. uber has taken the responsibility of this project. Otherwise, we need to switch all our mock to [mockery](https://vektra.github.io/mockery/latest/), which is time-consuming at this time.
