### ISSUE TITLE
`stern` log collector prevents `rad run` from working

### ISSUE THREAD

**Issue by loekd** [radius-project/radius#7565]
### Steps to reproduce

- Create an application that runs more than 10 containers. In my case, I'm running a few (test) MongoDb containers and a Jaeger Daemonset next to my App.
- Execute `rad run`
- This will fail because of `stern` 
- Notice the error message

### Observed behavior

This is the output that is generated:

```
Starting log stream...

+ backendapi-58d766c8f9-2mbjd › backendapi
+ backendapi-58d766c8f9-2mbjd › daprd
+ frontend-754c68fd46-lw2l8 › frontend
+ jaeger-soasl3vdz6bj4-j995d › jaeger
+ jaeger-soasl3vdz6bj4-jfvkt › jaeger
+ mongo-dkna2yzxpcneq-67645c4fd-8g4gl › mongo
+ mongo-iqc733ktshkvc-78f5795dd9-rsf49 › mongo
+ mongo-iwp4qeiff62fy-6c8c7ff769-db6sg › mongo
+ mongo-p6ua5xnjo33vu-6c64d6d476-6fqw2 › mongo
failed to retry: context canceled
- mongo-dkna2yzxpcneq-67645c4fd-8g4gl › mongo
- mongo-iqc733ktshkvc-78f5795dd9-rsf49 › mongo
- mongo-iwp4qeiff62fy-6c8c7ff769-db6sg › mongo
- jaeger-soasl3vdz6bj4-j995d › jaeger
- mongo-p6ua5xnjo33vu-6c64d6d476-6fqw2 › mongo
Cannot list ReplicaSets with error: Get "https://aks-dns.hcp.northeurope.azmk8s.io:443/apis/apps/v1/namespaces/radius-system/replicasets?labelSelector=app.kubernetes.io%2Fname%3Ddashboard%2Capp.kubernetes.io%2Fpart-of%3Dradius": context canceled
- backendapi-58d766c8f9-2mbjd › backendapi
- frontend-754c68fd46-lw2l8 › frontend
Cannot list ReplicaSets with error: Get "https://aks-dns.hcp.northeurope.azmk8s.io:443/apis/apps/v1/namespaces/azure-radius/replicasets?labelSelector=radapp.io%2Fapplication%3Dradius": context canceled
- jaeger-soasl3vdz6bj4-jfvkt › jaeger
Error: stern reached the maximum number of log requests (10), use --max-log-requests to increase the limit
```

### Desired behavior

I would like to be able to run my application without `stern` preventing me.

### Workaround

I am using Recipes to create MongoDb and Jaeger. 
As a workaround, I can remove the label `radapp.io/application': context.application == null ? '' : context.application.name` from the created Deployment. This way the output won't be collected by `stern`, and the app will run. (But I won't see the logs.)

### rad Version

```
RELEASE   VERSION   BICEP     COMMIT
0.33.0    v0.33.0   0.33.0    6ffdc9980420c00f7af35b024dd0e62e598efef2
```

### Operating system

Windows 11 (Radius runs on AKS)

### Additional context

The `stern` tool allows specifying a configuration file, but adding it here `%APPDATA%/.config/stern/config.yaml` did not help.

### Would you like to support us?

- [ ] Yes, I would like to support you

[AB#12318](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/12318)

**Comment by rynowak** [comment]
@loekd - thanks for filing this. We should definitely make sure a log failure isn't blocking. I think we could also definitely increase the number of logs we're following.

The configuration for this is here: https://github.com/radius-project/radius/blob/4d7ee44f83bac76ad7768154a5c90d4cc080d200/pkg/cli/kubernetes/logstream/stern.go#L84

**Comment by ytimocin** [comment]
Here is the link to the error in the stern repo: https://github.com/stern/stern/blob/6afabdeb0bc3871d1b670b4e312b11563a775259/stern/stern.go#L195.
