### ISSUE TITLE
Gateway does not properly support SignalR

### ISSUE THREAD

**Issue by loekd** [radius-project/radius#7590]
### Steps to reproduce

- Create a container that exposes a SignalR hub.
- Create a (SPA) frontend container that hosts a web page which connects to it.
- Create a Gateway that exposes the SignalR hub and the Frontend.
Example yaml:

```
resource gateway 'Applications.Core/gateways@2023-10-01-preview' = {
  name: 'gateway'
  properties: {
    application: application 
    environment: environment
    routes: [
      {
        path: '/api' //REST API
        destination: 'http://${api.name}:${api.properties.container.ports.web.containerPort}'
      }
      {
        path: '/dispatchhub' //SignalR Hub
        destination: 'http://${api.name}:${api.properties.container.ports.web.containerPort}'
      }      
      {
        path: '/' //frontend index.html
        destination: 'http://${frontend.name}:${frontend.properties.container.ports.web.containerPort}'
      }
    ]
  }
}
```

### Observed behavior

- After 15 seconds, the server returns HTTP Status Code 504.
  - 504 Gateway Timeout (from service worker)
- The body will be: `upstream request timeout`
- The server Response header will be: `envoy`
- SignalR connection is lost

![image](https://github.com/radius-project/radius/assets/12125836/ddf51414-aaf1-406a-88cf-b16f7e02d822)
![image](https://github.com/radius-project/radius/assets/12125836/dbcdf4b5-dacc-4a93-b140-0f60d1015ea5)

### Desired behavior

- I'd like SignalR to keep working indefinitely

### Workaround

- Connecting directly to the application container works, but is not great from a CORS perspective.

### rad Version

```
RELEASE   VERSION   BICEP     COMMIT
0.33.0    v0.33.0   0.33.0    6ffdc9980420c00f7af35b024dd0e62e598efef2
```

### Operating system

Windows 11 x64

### Additional context

- Envoy does support [wss](https://www.envoyproxy.io/docs/envoy/latest/start/sandboxes/websocket)
- Contour does so as [well](https://projectcontour.io/docs/1.24/config/websockets/), patching the `HTTPProxy` helps, but is not the way to go imo

### Would you like to support us?

- [ ] Yes, I would like to support you

[AB#12363](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/12363)

**Comment by willtsai** [comment]
Note from the triage team: we don't think there should be limitations for applications moving to Radius, seems like something about the way we are using Contour is causing this issue and we should fix that.

**Comment by ytimocin** [comment]
Adding a very short design document: https://gist.github.com/ytimocin/ada142d271a984e9e88f9249c82c82e6.

**Comment by ytimocin** [comment]
Hi @loekd! If you are using edge version of Radius, could you try adding `enableWebsockets: true` to the route(s) you need and try again?
