### ISSUE TITLE
Use typed mocks 

### ISSUE THREAD

**Issue by rynowak** [radius-project/radius#7592]
### Area for Improvement

We can update our use of gomock to generate typed functions by passing in `-typed`. 

From the command line help:

```
  -typed
    	Generate Type-safe 'Return', 'Do', 'DoAndReturn' function
```

### Observed behavior

We don't pass in `-typed` so none of the gomock generated code is strongly typed. This slows down development for us, because it's possible to get the wrong signatures.

### Desired behavior

Use `-typed` everywhere we create a mock. This shouldn't break us if we already wrote correct code.

### Proposed Fix

- Do a search for `//go:generate mockgen`. Replace with `//go generate mockgen -typed`.
- Run `make generate-go`.
- Run the tests (should work). 

### rad Version

asdf

### Would you like to support us?

- [ ] Yes, I would like to support you

[AB#12367](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/12367)

**Comment by kachawla** [comment]
@superbeeny could you comment on this with `/assign` to assign this issue to yourself, since you have a PR for this :)
