### ISSUE TITLE
Rad Init fails with Badrequest 

### ISSUE THREAD

**Issue by johnden12** [radius-project/radius#7596]
### Steps to reproduce

1. Create a new AKS Cluster  using Kubernetes version: 1.28.9
2. Connect to the newly created cluster and ensure Kubectl context is correct
3. Do a clean install of Radius v0.33.0
4. Create a new folder for the application `mkdir RadiusDemo`
5. cd to the created directory `cd RadiusDemo`
6. Execute `rad init`

### Observed behavior

The initialisation fails with the following message:

Initializing Radius. This may take a minute or two...

✅ Use existing Radius 0.33.0 install on ******************************************
✅ Use existing environment default
🕒 Scaffold application RadiusDemo
⏳ Update local configuration

Error: {
          "code": "BadRequest",
                                 "message": "Application namespace 'default-RadiusDemo' could not be created: the combination of application and environment names is too long."
                                                                                                                                                                                }

                                                                                                                                                                                 TraceId:  3067e50df532cc056b493f15f74f2ac1

### Desired behavior

The initialisation should succesfully complet without any error

### Workaround

None

### rad Version

v0.33.0

### Operating system

Windows 11

### Would you like to support us?

- [ ] Yes, I would like to support you

[AB#12377](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/12377)

**Comment by ytimocin** [comment]
Hi @johnden12! Thanks for reporting this issue! I think this is a similar issue: #7528. We should be looking at this soon.

**Comment by willtsai** [comment]
@johnden12 - the fix for this issue has been merged into `main` and should be resolved in the upcoming release. If you still experience it after the next release (`v0.34` onwards), please reopen this issue, thanks!
