### ISSUE TITLE
Functional test runs triggered by a push to main fail

### ISSUE THREAD

**Issue by rynowak** [radius-project/radius#7668]
### Area for Improvement

Functional Testing

### Observed behavior

When a commit is pushed to main, this triggers a run of the functional tests. These function test runs always fail. 

Here's an example: https://github.com/radius-project/radius/actions/runs/9404321768/job/25902966666

### Desired behavior

I can think of two options for this:

- Don't run functional tests on push to main. I'm not sure why we need this.
- Fix the workflow so that it works on a push to main.

### rad Version

asdf

### Would you like to support us?

- [ ] Yes, I would like to support you

[AB#12476](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/12476)

**Comment by lakshmimsft** [comment]
We determined that functional tests are not being run on push/merge to main at this time and we're not seeing failures for this error. Closing at this time.
