### ISSUE TITLE
Large number of resource groups that begin with `radtest-` in Azure subscription

### ISSUE THREAD

**Issue by lakshmimsft** [radius-project/radius#7677]
### Area for Improvement

There are ~231 resource groups in Radius Dev subscription which begin with `radtest-`. These would be created during test pipeline runs but they are either not being deleted after the run completes or they are not picked up by purge-test-resources.yaml later and deleted.
Radius Test subscription has a fewer number ~24 resource groups. 

1. Is the purge-test-resources.yaml is only running against Radius Test subscription? Pls review workflow(s) which should delete resource groups upon test runs and check if working as expected.
2. Delete older resource groups which have names that start with `radtest-`

### Desired behavior

Resource groups are deleted after test run completion.
purge-test-resources.yaml is running as expected.

### rad Version

NA

### Operating system

NA

### Additional context

NA

### Would you like to support us?

- [ ] Yes, I would like to support you

[AB#12488](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/12488)

**Comment by ytimocin** [comment]
I created a script that deletes all the resource groups that start with `radtest-` and have 0 resources. It is running now, and it should finish in less than an hour. After that we can check if we will still see these resource groups get built up.

**Comment by ytimocin** [comment]
> There are 17 resource groups, within two different subscriptions, that have at least one resource. I checked all these resource groups, and all the resources are storage accounts. There may be a pattern here like storage account not being deleted, functional test failing, and resource group becoming dangling as well as the storage account.

After [my PR](https://github.com/radius-project/radius/pull/7683) number or resource groups went up to 25. After the functional tests of the same PR finished running, this number didn't go down. So, yes, we are definitely not deleting resource groups after running functional tests.

Please review the PR linked above.

**Comment by lakshmimsft** [comment]
@ytimocin  Radius Dev still has around 11 resource groups starting with 'radtest'. They seem be created roughly between March8-11 and have a identity and storage account resource. Checking, if they should also be deleted.

**Comment by kachawla** [comment]
@lakshmimsft @ytimocin thanks for catching and fixing this. I'm curious how did we end up with radtest resource groups in Radius Dev, they should only be getting created under test subscription did we find out where did they come from?

**Comment by ytimocin** [comment]
@kachawla not exactly sure. Functional tests create resource groups with the prefix of `radtest-func` not just `radtest`. Maybe the ones that start with `radtest` were just tests or previous versions of our functional tests.

**Comment by kachawla** [comment]
> @kachawla not exactly sure. Functional tests create resource groups with the prefix of `radtest-func` not just `radtest`. Maybe the ones that start with `radtest` were just tests or previous versions of our functional tests.

@ytimocin I meant they should not be getting creating in the Dev subscription. Just checked and noticed a bunch of new `radtest-***-shared` resource groups have been created in this week as well. I'm going to log an issue to investigating what's creating them in the dev subscription. All functional tests should target test subscription.

**Comment by ytimocin** [comment]
> > @kachawla not exactly sure. Functional tests create resource groups with the prefix of `radtest-func` not just `radtest`. Maybe the ones that start with `radtest` were just tests or previous versions of our functional tests.
> 
> @ytimocin I meant they should not be getting creating in the Dev subscription. Just checked and noticed a bunch of new `radtest-***-shared` resource groups have been created in this week as well. I'm going to log an issue to investigate what's creating them in the dev subscription. All functional tests should target test subscription.

Interesting. Do you see more than 11 like other than the ones below? I didn't delete these 11 resource groups on purpose because they have resources inside. If you see new resource groups that were created **this week**, we should definitely create an issue to investigate.

I also couldn't find the creation dates for these resource groups on the portal. Do you know how we can see that? That would be helpful to me.

![image](https://github.com/radius-project/radius/assets/5220939/c7c3b955-a7c0-4831-8db8-92b2da8d7369)

**Comment by kachawla** [comment]
> > > @kachawla not exactly sure. Functional tests create resource groups with the prefix of `radtest-func` not just `radtest`. Maybe the ones that start with `radtest` were just tests or previous versions of our functional tests.
> > 
> > 
> > @ytimocin I meant they should not be getting creating in the Dev subscription. Just checked and noticed a bunch of new `radtest-***-shared` resource groups have been created in this week as well. I'm going to log an issue to investigate what's creating them in the dev subscription. All functional tests should target test subscription.
> 
> Interesting. Do you see more than 11 like other than the ones below? I didn't delete these 11 resource groups on purpose because they have resources inside. If you see new resource groups that were created **this week**, we should definitely create an issue to investigate.

You are right, these are the only ones I see and all of them were created 3 months ago. I was making a mistake when converting epoch timestamp which made me think they were created this week.

> I also couldn't find the creation dates for these resource groups on the portal. Do you know how we can see that? That would be helpful to me.

We add a [creationTime tag on test resource groups](https://github.com/radius-project/radius/blob/13d50f7b02f77b868bebb9a3582953d3bc7c9f2d/.github/workflows/functional-test.yaml#L416), you can find them in tags in resource group overview page on the portal.
