### ISSUE TITLE
Long Running tests on azure failing Test_TerraformRecipe_KubernetesPostgres

### ISSUE THREAD

**Issue by vishwahiremat** [radius-project/radius#7705]
### Steps to reproduce

Long running test pipeline is failing consistently while running Test_TerraformRecipe_KubernetesPostgres.
https://github.com/radius-project/radius/actions/runs/9606058736/job/26494919131

### Observed behavior

=== Failed
=== FAIL: test/functional-portable/corerp/noncloud/resources Test_TerraformRecipe_KubernetesPostgres/deploy_testdata/corerp-resources-terraform-postgres.bicep (39.39s)
    rptest.go:391: running step 0 of 1: deploy testdata/corerp-resources-terraform-postgres.bicep
    deployexecutor.go:80: deploying deploy testdata/corerp-resources-terraform-postgres.bicep from file testdata/corerp-resources-terraform-postgres.bicep
    cli.go:394: [heartbeat] command rad deploy /home/runner/work/radius/radius/test/functional-portable/corerp/noncloud/resources/testdata/corerp-resources-terraform-postgres.bicep --parameters moduleServer=http://tf-module-server.radius-test-tf-module-server.svc.cluster.local --parameters userName=postgres --parameters ***' is still running after 10.000704275s
    cli.go:394: [heartbeat] command rad deploy /home/runner/work/radius/radius/test/functional-portable/corerp/noncloud/resources/testdata/corerp-resources-terraform-postgres.bicep --parameters moduleServer=http://tf-module-server.radius-test-tf-module-server.svc.cluster.local --parameters userName=postgres --parameters ***' is still running after 20.00092529s
    cli.go:394: [heartbeat] command rad deploy /home/runner/work/radius/radius/test/functional-portable/corerp/noncloud/resources/testdata/corerp-resources-terraform-postgres.bicep --parameters moduleServer=http://tf-module-server.radius-test-tf-module-server.svc.cluster.local --parameters userName=postgres --parameters ***' is still running after 30.000992036s
    cli.go:341: [rad] Building /home/runner/work/radius/radius/test/functional-portable/corerp/noncloud/resources/testdata/corerp-resources-terraform-postgres.bicep...
    cli.go:341: [rad] Deploying template '/home/runner/work/radius/radius/test/functional-portable/corerp/noncloud/resources/testdata/corerp-resources-terraform-postgres.bicep' into environment 'kind-radius' from workspace 'radlrtest00-aks-admin'...
    cli.go:341: [rad] 
    cli.go:341: [rad] Deployment In Progress...
    cli.go:341: [rad] 
    cli.go:341: [rad] Error: {
    cli.go:341: [rad]   "code": "DeploymentFailed",
    cli.go:341: [rad]   "message": "At least one resource deployment operation failed. Please see the details for the specific operation that failed.",
    cli.go:341: [rad]   "target": "/planes/radius/local/resourceGroups/kind-radius/providers/Microsoft.Resources/deployments/rad-deploy-5590f9c9-1a00-48c5-9191-5f[83](https://github.com/radius-project/radius/actions/runs/9606058736/job/26494919131#step:23:84)f249202c",
    cli.go:341: [rad]   "details": [
    cli.go:341: [rad]     {
    cli.go:341: [rad]       "code": "ResourceDeploymentFailure",
    cli.go:341: [rad]       "message": "Failed",
    cli.go:341: [rad]       "target": "/planes/radius/local/resourceGroups/kind-radius/providers/Applications.Core/extenders/pgs-resources-terraform-pgsapp",
    cli.go:341: [rad]       "details": [
    cli.go:341: [rad]         {
    cli.go:341: [rad]           "code": "RecipeDeploymentFailed",
    cli.go:341: [rad]           "message": "terraform apply failure: exit status 1\n\nError: error detecting capabilities: error PostgreSQL version: dial tcp 172.16.69.137:5432: connect: connection refused\n\n  with module.defaultpostgres.postgresql_database.pg_db_test,\n  on .terraform/modules/defaultpostgres/main.tf line 77, in resource \"postgresql_database\" \"pg_db_test\":\n  77: resource postgresql_database \"pg_db_test\" {\n\n"
    cli.go:341: [rad]         }
    cli.go:341: [rad]       ]
    cli.go:341: [rad]     },
    cli.go:341: [rad]     {
    cli.go:341: [rad]       "code": "OK",
    cli.go:341: [rad]       "message": "",
    cli.go:341: [rad]       "target": "/planes/radius/local/resourceGroups/kind-radius/providers/Applications.Core/environments/corerp-resources-terraform-pg-env"
    cli.go:341: [rad]     },
    cli.go:341: [rad]     {
    cli.go:341: [rad]       "code": "OK",
    cli.go:341: [rad]       "message": "",
    cli.go:341: [rad]       "target": "/planes/radius/local/resourceGroups/kind-radius/providers/Applications.Core/applications/corerp-resources-terraform-pg-app"
    cli.go:341: [rad]     }
    cli.go:341: [rad]   ]
    cli.go:341: [rad] }
    cli.go:341: [rad] 
    cli.go:341: [rad] TraceId:  7ab8b316faf63ca7d6c3f2437d771bf5
    cli.go:341: [rad] 
    cli.go:341: [rad] 
    deployexecutor.go:83: 
        	Error Trace:	/home/runner/work/radius/radius/test/step/deployexecutor.go:83
        	            				/home/runner/work/radius/radius/test/rp/rptest.go:3[92](https://github.com/radius-project/radius/actions/runs/9606058736/job/26494919131#step:23:93)
        	Error:      	Received unexpected error:
        	            	code DeploymentFailed: err At least one resource deployment operation failed. Please see the details for the specific operation that failed.
        	Test:       	Test_TerraformRecipe_KubernetesPostgres/deploy_testdata/corerp-resources-terraform-postgres.bicep
        	Messages:   	failed to deploy deploy testdata/corerp-resources-terraform-postgres.bicep
    --- FAIL: Test_TerraformRecipe_KubernetesPostgres/deploy_testdata/corerp-resources-terraform-postgres.bicep (39.39s)

### Desired behavior

test should succesfully pass without failure

### rad Version

main branch

### Would you like to support us?

- [ ] Yes, I would like to support you

[AB#12609](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/12609)

**Comment by ytimocin** [comment]
I restarted the `core-dns` pods and this issue disappeared.

**Comment by kachawla** [comment]
Should we close this @lakshmimsft @ytimocin?

**Comment by vishwahiremat** [comment]
yes, i think this can be closed. this issue is fixed in https://github.com/radius-project/radius/pull/7707.
