### ISSUE TITLE
Publish magpiego as a multi-arch image

### ISSUE THREAD

**Issue by rynowak** [radius-project/radius#7743]
### Area for Improvement

Functional testing

### Observed behavior

`magpiego` is an image we use for functional testing. Right now this is only published as an amd64 image. 

For users on MacOS running the functional tests locally will fail with `exec format error` unless they have Rosetta installed. 

### Desired behavior

Functional testing just works. 

### Proposed Fix

Publish `magpiego` as a multi-architecture image.

### rad Version

aaaa

### Operating system

MacOS + M1 chip

### Additional context

Found while debugging with @superbeeny 

### Would you like to support us?

- [ ] Yes, I would like to support you

[AB#12849](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/12849)

**Comment by nicolejms** [comment]
just change 2 docker file definitions

**Comment by rynowak** [comment]
Some proof of what's missing:

- (supports multiple architectures) https://github.com/radius-project/radius/pkgs/container/ucpd
- (single architecture) https://github.com/radius-project/radius/pkgs/container/magpiego

**Good**

<img width="930" alt="image" src="https://github.com/user-attachments/assets/301e1e27-7524-4390-a01b-23073d2c7765">


**Bad**

(notice the lack of architectures tab)

<img width="912" alt="image" src="https://github.com/user-attachments/assets/bb1130ce-c81b-4d3d-8d3f-c62f4635777a">

**Comment by rynowak** [comment]
I don't think this is fixed yet. Check the link to the magpiego image. 

PR #7745 updated the dockerfiles, but I think we need makefile changes too.

**Comment by ytimocin** [comment]
![image](https://github.com/user-attachments/assets/79773f41-a4aa-48ef-aa80-cfe44f98060f)

![image](https://github.com/user-attachments/assets/96d49493-ddea-44cc-ae15-b7123512d4ef)
