### ISSUE TITLE
radius uninstall should provide a way for users to delete all data

### ISSUE THREAD

**Issue by nithyatsu** [radius-project/radius#7764]
Today, when we uninstall radius, we uninstall "control-plane", while retaining all data created so far. 
Sometimes this is not what we want and would like to have a really clean start. Today we can do this by deleting `radius-system` namespace using Kubernetes commands. 

It would help if radius provided the ability to uninstall/ reinstall with an option to clear all data.

[AB#12893](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/12893)

**Comment by lakshmimsft** [comment]
This has been completed. Thanks @lbzss!!
