### ISSUE TITLE
`Error connecting to PostgreSQL server` error message in Long Running tests

### ISSUE THREAD

**Issue by ytimocin** [radius-project/radius#7767]
### Steps to reproduce

1. Please go to Actions tab on Radius GitHub Page
2. Go to Long-Running Test on Azure
3. Check a few failed runs

### Observed behavior

{
    cli.go:341: [rad]       "code": "ResourceDeploymentFailure",
    cli.go:341: [rad]       "message": "Failed",
    cli.go:341: [rad]       "target": "/planes/radius/local/resourceGroups/kind-radius/providers/Applications.Core/extenders/pgs-resources-terraform-pgsapp",
    cli.go:341: [rad]       "details": [
    cli.go:341: [rad]         {
    cli.go:341: [rad]           "code": "RecipeDeploymentFailed",
    cli.go:341: [rad]           "message": "terraform apply failure: exit status 1\n\nError: Error connecting to PostgreSQL server postgres.corerp-resources-terraform-pg-app.svc.cluster.local (scheme: postgres): dial tcp 172.16.245.108:5432: connect: connection refused\n\n  with module.defaultpostgres.postgresql_database.pg_db_test,\n  on .terraform/modules/defaultpostgres/main.tf line 77, in resource \"postgresql_database\" \"pg_db_test\":\n  77: resource postgresql_database \"pg_db_test\" {\n\n"
    cli.go:341: [rad]         }
    cli.go:341: [rad]       ]
    cli.go:341: [rad]     }

### Desired behavior

Connection to the PostgreSQL Server should work fine.

### Workaround

Example run: https://github.com/radius-project/radius/actions/runs/10100253542/job/27932380733

### rad Version

edge

### Would you like to support us?

- [ ] Yes, I would like to support you

[AB#12896](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/12896)

**Comment by lakshmimsft** [comment]
I think we can close this issue @ytimocin. The PRs to update registries and increase timeout helped with this. https://github.com/radius-project/radius/pull/7772

**Comment by ytimocin** [comment]
It was due to a certificate error that the core-dns pods weren't working properly. Restarting them actually fixed the issue. cc/ @lakshmimsft
