### ISSUE TITLE
`Key based authentication is not permitted on this storage account` in `assets` workflow

### ISSUE THREAD

**Issue by ytimocin** [radius-project/radius#7780]
### Steps to reproduce

The last few runs of the **assets** workflow (triggered by a merge to main) is failing with the following error:

`ERROR: Key based authentication is not permitted on this storage account.`

### Observed behavior

**assets** workflow is failing in the `Upload install.sh` step: https://github.com/radius-project/radius/blob/main/.github/workflows/assets.yaml#L36.

There is a connection string passed into the `bacongobbler/azure-blob-storage-upload@v3.0.0` action. We receive the following error:

`ERROR: Key based authentication is not permitted on this storage account.`

### Desired behavior

Connection to the storage account should work fine, thus making **assets** workflow run successfully.

### Workaround

Not sure if this is something that we could handle in the storage account (the one that we use in this workflow) level. I am thinking that there might be an update to the storage account resources in general that would block some types of authentications if a permission was not given.

### rad Version

edge

### Additional context

Link to a failing run: https://github.com/radius-project/radius/actions/runs/10205813601/job/28237404786.

### Would you like to support us?

- [ ] Yes, I would like to support you

[AB#12930](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/12930)

**Comment by ytimocin** [comment]
Same issue was reported a few days ago in another repository: https://github.com/OfficeDev/teams-toolkit/issues/12092.

**Comment by lakshmimsft** [comment]
The assets workflow is now deleted. Closing this issue.
