### ISSUE TITLE
Remove/disable assets workflow

### ISSUE THREAD

**Issue by sk593** [radius-project/radius#7800]
### Steps to reproduce

The assets workflow has started to fail. We don't use any of the assets that get uploaded so these should be disabled and/or removed: https://github.com/radius-project/radius/blob/main/.github/workflows/assets.yaml

### Desired behavior

Either we disable and eventually delete the workflow or we update the workflow so it passes. We don't pull assets from Azure storage anymore so this shouldn't be needed

### rad Version

GH actions runs 

### Would you like to support us?

- [ ] Yes, I would like to support you

[AB#12960](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/12960)

**Comment by ytimocin** [comment]
Related issue: https://github.com/radius-project/radius/issues/7780.

**Comment by ytimocin** [comment]
I think removing is the way to go **if** we are sure that the assets generated are not being used. cc/ @willdavsmith

**Comment by sk593** [comment]
We've disabled this for now. We'll go ahead with the delete if there's no unexpected issues
