### ISSUE TITLE
Revert bicep build authentication workaround

### ISSUE THREAD

**Issue by sk593** [radius-project/radius#7804]
### Area for Improvement

There are a few places in our code where we had to implement workarounds because of this issue: https://github.com/Azure/bicep/issues/14774. The workaround is explained in the issue and removes az auth

### Desired behavior

Once there is a fix for the above issue, we should remove the workarounds in our validate-bicep and functional test workflows 

Places we use the workaround: 
https://github.com/radius-project/radius/blob/3ddb61eb84c4545f06fa6035009dec5c977f59e4/.github/workflows/functional-test-cloud.yaml#L376
https://github.com/radius-project/radius/blob/3ddb61eb84c4545f06fa6035009dec5c977f59e4/.github/workflows/functional-test-noncloud.yaml#L349
https://github.com/radius-project/radius/blob/3ddb61eb84c4545f06fa6035009dec5c977f59e4/.github/workflows/validate-bicep.yaml#L72

### rad Version

GH actions radius version

### Would you like to support us?

- [ ] Yes, I would like to support you

[AB#12961](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/12961)

**Comment by sk593** [comment]
> > ### Area for Improvement
> > There are a few places in our code where we had to implement workarounds because of this issue: [Azure/bicep#14774](https://github.com/Azure/bicep/issues/14774). The workaround is explained in the issue and removes az auth
> 
> @sk593 can you please add a link to the workaround.

Sure, the workaround is mentioned in the linked issue. This is the comment that explains the workaround: https://github.com/Azure/bicep/issues/14774#issuecomment-2278836682

**Comment by kachawla** [comment]
> > > ### Area for Improvement
> > > There are a few places in our code where we had to implement workarounds because of this issue: [Azure/bicep#14774](https://github.com/Azure/bicep/issues/14774). The workaround is explained in the issue and removes az auth
> > 
> > 
> > @sk593 can you please add a link to the workaround.
> 
> Sure, the workaround is mentioned in the linked issue. This is the comment that explains the workaround: https://github.com/Azure/bicep/issues/14774#issuecomment-2278836682

@sk593 this came up in triage discussion, it was meant for link to code paths where we have implemented the workaround. Could you please update the issue description to include those links? Mainly to make it easily discoverable for whoever picks this issue up.

**Comment by sk593** [comment]
> > > > ### Area for Improvement
> > > > There are a few places in our code where we had to implement workarounds because of this issue: [Azure/bicep#14774](https://github.com/Azure/bicep/issues/14774). The workaround is explained in the issue and removes az auth
> > > 
> > > 
> > > @sk593 can you please add a link to the workaround.
> > 
> > 
> > Sure, the workaround is mentioned in the linked issue. This is the comment that explains the workaround: [Azure/bicep#14774 (comment)](https://github.com/Azure/bicep/issues/14774#issuecomment-2278836682)
> 
> @sk593 this came up in triage discussion, it was meant for link to code paths where we have implemented the workaround. Could you please update the issue description to include those links? Mainly to make it easily discoverable for whoever picks this issue up.

ah, I misunderstood the comment. just added the code links
