### ISSUE TITLE
Update TypeSpec npm packages in dev container

### ISSUE THREAD

**Issue by brooke-hamilton** [radius-project/radius#7812]
### Area for Improvement

The `postCreateCommand` in the dev container runs `npm ci` in the `typespec` folder. Some of the packages specified in the `package-lock.json` file are out of date. 

### Observed behavior

Building and running the dev container shows that some of the packages need to be updated.

### Desired behavior

Packages should be current.

### Proposed Fix

1. Run `npm update` in the `typespec` folder and submit a PR for the changes.
2. Find a way to add this folder to the dependabot checks.

### rad Version

0.36

### Would you like to support us?

- [ ] Yes, I would like to support you

[AB#12985](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/12985)

**Comment by rynowak** [comment]
@ytimocin @brooke-hamilton do we know why this isn't covered by depdendabot already?

**Comment by ytimocin** [comment]
> @ytimocin @brooke-hamilton do we know why this isn't covered by depdendabot already?

I will check this.

Another update: when we run `npm update` and update package-lock.json, our tsp files need a lot of updates too. This work is probably bigger (in terms of scope) than just running the command.

**Comment by ytimocin** [comment]
Unassigned myself from this issue for now.

**Comment by ytimocin** [comment]
Completed
