### ISSUE TITLE
"rad bicep publish" Fails to Publish Bicep Files to ECR

### ISSUE THREAD

**Issue by vishwahiremat** [radius-project/radius#7855]
### Steps to reproduce

1) login to acr
`aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin <account-name>.dkr.ecr.us-east-2.amazonaws.com`
2) publish bicep file to ECR
`rad bicep publish --file test/testrecipes/test-bicep-recipes/rabbitmq-recipe.bicep --target br:<account-name>.dkr.ecr.us-east-2.amazonaws.com/test-ecr:latest`

### Observed behavior

Throws `blob upload invalid` error

`
Failed to publish Bicep file "test/testrecipes/test-bicep-recipes/rabbitmq-recipe.bicep" to "<account-name>.dkr.ecr.us-east-2.amazonaws.com/test-ecr:1.0"
Something went wrong Cause: PUT "https://<account-name>.dkr.ecr.us-east-2.amazonaws.com/v2/test-private-ecr/blobs/uploads/47552bfb-e8f7-41ad-9c07-310446dc14?digest=sha256%3Ae3b0c44298fc1c149afbf4c8996fb927ae41e4649b934ca495991b7852b855": response status code 400: blob upload invalid: The upload with id '47552bfb-e8f7-41ad-9c07-314186dc14' in the repository with name 'test-ecr' in registry with id '<account-name>' cannot be completed because it does not have any parts.
`

### Desired behavior

Should be able to successfully upload bicep to ECR

### rad Version

RELEASE   VERSION   BICEP     COMMIT
0.37.0    v0.37.0   0.29.47   b1a78222b715a29fd5d76858403bec8f686b732e

### Would you like to support us?

- [ ] Yes, I would like to support you

[AB#13092](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/13092)

**Comment by rynowak** [comment]
Possibly a similar issue that was worked around: https://git.homegu.com/devcontainers/cli/issues/814
