### ISSUE TITLE
Implementation of Dapr Building Block: Configuration Store

### ISSUE THREAD

**Issue by SoTrx** [radius-project/radius#7889]
### Overview of feature request

The Dapr [configuration](https://docs.dapr.io/getting-started/quickstarts/configuration-quickstart/) building block allows for dynamic configuration updates, including feature flag management.

For Radius, supporting this building block could enhance the "code once, deploy everywhere" approach, as platform differences may necessitate the use of feature flags.

### Acceptance criteria

- A new Applications.Dapr/configurationStores resource can be created.
- A new local development recipe has been added, [using Redis as the backend](https://docs.dapr.io/reference/components-reference/supported-configuration-stores/redis-configuration-store/).

### Additional context

https://docs.dapr.io/developing-applications/building-blocks/configuration/

### Would you like to support us?

- [X] Yes, I would like to support you

[AB#13152](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/13152)

**Comment by lakshmimsft** [comment]
@SoTrx, thanks for your willingness to contribute! Pls don't hesitate to reach out for support.

**Comment by SoTrx** [comment]
## Changes for users

This update introduces the Dapr Configuration Building Block, enabling applications to consume configuration data as read-only key/value pairs and receive notifications via callback when changes occur. The configuration is stored in a backing service, which can be any [Dapr-supported service](https://docs.dapr.io/reference/components-reference/supported-configuration-stores/). From a Radius user perspective, the configuration store is accessed as `Applications.Dapr/configurationStores`.
```bicep
resource myapp 'Applications.Core/containers@2023-10-01-preview' = {
  name: '${baseName}-ctnr'
  properties: {
    connections: {
      config: {
        source: configStore.id
      }
    }
  ...
  }
}

resource configStore 'Applications.Dapr/configurationStores@2023-10-01-preview' = {
  name: '${baseName}-cpn'
  properties: {
    application: app.id
    environment: env.id
  }
}
```

Using a connection with a `configurationStore` injects the corresponding Dapr component name into the app container environment variable as `CONNECTION_$(connection_name)_COMPONENTNAME`. This allows the application to access the configuration as shown below:

```go
ctx := context.Background()
client, _:= dapr.NewClient()
// Retrieve the initial configuration values for key "config_key"
items, err := client.GetConfigurationItems(ctx, CONNECTION_CONFIG_COMPONENTNAME, ["config_key"])
// Subscribe to updates to the values of "config_key"
subId, _:= client.SubscribeConfigurationItems(ctx, CONNECTION_CONFIG_COMPONENTNAME, []string{"config_key"})
 ```


## Changes in Radius

This change adds the resource type `Applications.Dapr/ConfigurationStores` to the Dapr resource provider. This addition has no side effects on other resources in the provider.

This changes adds the resource type application.Dapr/ConfigurationStores to the Dapr resource provider. This addition has no side-effect on other resources in the provider. 

### Frontend
```tsp
model DaprConfigurationStoreResource
  is TrackedResourceRequired<
    DaprConfigurationStoreProperties,
    "DaprConfigurationStores"
  > {
  @doc("Configuration Store name")
  @key("configurationStoreName")
  @path
  @segment("configurationStores")
  name: ResourceNameString;
}

@doc("Dapr configuration store portable resource properties")
model DaprConfigurationStoreProperties {
  ...EnvironmentScopedResource;
  ...DaprResourceProperties;

  @doc("A collection of references to resources associated with the configuration store")
  resources?: ResourceReference[];

  ...RecipeBaseProperties;
}
```

### Inner representation
```go
type DaprConfigurationStore struct {
	v1.BaseResource

	 // (Properties common to other components)
	Properties DaprConfigurationStoreProperties `json:"properties"`

	// ResourceMetadata represents internal DataModel properties common to all portable resource types.
	datamodel.PortableResourceMetadata
}
```

### Example emitted component

```yaml
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: configstore
  [labels]
spec:
  type: configuration.redis
  metadata:
  - name: redisHost
    value: localhost:6379
  - name: redisPassword
    value: <PASSWORD>
```

Let me know If I need to add anything to this description
