### ISSUE TITLE
Dashboard access unavailable from kube port-forward, seems  because of http access auto switch to https

### ISSUE THREAD

**Issue by kevinz** [radius-project/radius#7890]
### Steps to reproduce

1. deploy radius  0.37 with k3d host on gcp compute engine 
2. finish installation follow the guide, without anything wrong
3. kubectl port-forward --namespace=radius-system svc/dashboard 7007:7007 --address 0.0.0.0
4. try to access dashboard with  compute vm's public ip:7007 in my browser

### Observed behavior

![image](https://github.com/user-attachments/assets/6cdefe6e-e5b7-4016-a88f-3a7fdda4c8ac)

![image](https://github.com/user-attachments/assets/56bd8179-297a-4e58-97df-add8ecfef48b)

### Desired behavior

 kubectl port-forward --namespace=default-demo svc/demo  5678:3000 --address 0.0.0.0

then access public:5678 for the demo page,  it can get the right present page without resource load problem

### rad Version

0.37.0

### Operating system

6.1.0-23-cloud-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.99-1 (2024-07-15) x86_64 GNU/Linux

### Would you like to support us?

- [ ] Yes, I would like to support you

[AB#13157](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/13157)

**Comment by lakshmimsft** [comment]
1. Could you pls provide more information in the 'Observed behaviour' section.
2. The port forward in the description (3.): kubectl port-forward --namespace=radius-system svc/dashboard 7007:7007 --address 0.0.0.0
Did we try to port forward to 80 as described in the documentation:
https://docs.radapp.io/guides/tooling/dashboard/overview/#accessing-the-dashboard

**Comment by ytimocin** [comment]
Since we didn't get the extra information needed to investigate this issue, we are closing this one. Feel free to reopen it and add more information.
