### ISSUE TITLE
Radius Long-Running Tests fail to delete namespaces when cleaning up cluster

### ISSUE THREAD

**Issue by willdavsmith** [radius-project/radius#7948]
### Steps to reproduce

This is an issue in the scheduled long-running tests. Here is an example: https://github.com/radius-project/radius/actions/runs/10896307972/job/30235920240

## Clean up cluster
```
...
delete all test namespaces
deleting namespaces: corerp-application-simple1
namespace "corerp-application-simple1" deleted
Error: The action 'Clean up cluster' has timed out after 60 minutes.
```

### Observed behavior

The "Clean up cluster" step will time out when trying to delete a namespace and fail the test. The namespace is not deleted.

### Desired behavior

The namespace should be successfully deleted and cleaned up so that the subsequent tests don't fail.

### Workaround

The problem resolves itself after a day or so, but repeats every week or so

### rad Version

9/20/24

### Operating system

Long-running tests

### Would you like to support us?

- [ ] Yes, I would like to support you

[AB#13220](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/13220)

**Comment by lakshmimsft** [comment]
Closing this as discussed. @ytimocin , @willdavsmith.
This issue has not occurred in past weeks (over a month). We will reopen if this recurs and we need to address this.
