### ISSUE TITLE
Add more detail to rad install kubernetes doc

### ISSUE THREAD

**Issue by brooke-hamilton** [radius-project/radius#7968]
## What content needs to be created or modified?
The [`rad install kubernetes`](https://docs.radapp.io/reference/cli/rad_install_kubernetes/) document explains that the command has the `--set` and `--set-file` options. We need more information in the text that explains what the available values are or how to discover the available values that can be set.

## Describe the solution you'd like
Provide an explanation of the available values or a link to another API command that allows a user to discover the values. Provide an example as well.

## Where should the new material be placed?
Include in the existing help document.

## The associated pull request from the Radius code repo, if applicable
N/A

## Additional context
N/A

[AB#13253](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/13253)

**Comment by ckansara16** [comment]
Hello team, i would like to start my contribution from issue. can you please assign to me.
Thanks,
Chintan Kansara

**Comment by Reshrahim** [comment]
@ckansara16 Thank you for getting started on the contributions. You can comment `/assign` in the issue to assign it to urself.
