### ISSUE TITLE
enable unit tests for postgres datastore in Radius

### ISSUE THREAD

**Issue by nithyatsu** [radius-project/radius#7976]
Once https://github.com/radius-project/radius/issues/7975 is complete, we should make sure there is good test coverage for the feature. 

[AB#13381](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/13381)

**Comment by lakshmimsft** [comment]
Unit Tests should be included as part of #7975 implementation
