### ISSUE TITLE
Radius should support postgres datastore for users

### ISSUE THREAD

**Issue by nithyatsu** [radius-project/radius#7977]
As a user, I want to be able to use Postgres DB as my Radius datastore. I should have the option of using a pre-existing Postgres database, or optionally setup and use Postgres container as part of Radius installation.

As part of rad init and rad install, we should provide an option to choose postgres as datastore. We should also provide the users with an option between BYOD and installing postgres as part of Radius install. Upon choosing Postgres, we should setup postgres container ( if required), configure the postgres to have ucp and applications-rp databases and corresponding users, and neccessary tables for the 2 services. 

[AB#13382](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/13382)

**Comment by lakshmimsft** [comment]
included this requirement in #7975
