### ISSUE TITLE
Adding Postgres install to the radius helm chart

### ISSUE THREAD

**Issue by superbeeny** [radius-project/radius#8071]
### Overview of feature request

Installing postgres as a component of radius

### Acceptance criteria

Postgress is installed and initialized correctly

### Would you like to support us?

- [X] Yes, I would like to support you

[AB#13715](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/13715)

**Comment by brooke-hamilton** [comment]
@superbeeny Please help us fill out this feature request. Please fill out the sections with more details. For example, is the feature is optional, how is it configured, etc. We need enough detail to be able to decide whether to include the feature in the project, and if so, how to set the priority.

**Comment by ytimocin** [comment]
cc/ @superbeeny

**Comment by superbeeny** [comment]
Hi Guys, I'm on vacation this week so I may or may not get to this.

**Comment by superbeeny** [comment]
Closing as duplicate to use #8096
